//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Views.LecteurReseau {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LecteurReseauRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LecteurReseauRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TetraTech.TTProjetPlus.Views.LecteurReseau.LecteurReseauRessources", typeof(LecteurReseauRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir un serveur ....
        /// </summary>
        public static string ChooseServer {
            get {
                return ResourceManager.GetString("ChooseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecter un lecteur réseau.
        /// </summary>
        public static string ConnectReader {
            get {
                return ResourceManager.GetString("ConnectReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecter un lecteur réseau spécial.
        /// </summary>
        public static string ConnectReaderSpecial {
            get {
                return ResourceManager.GetString("ConnectReaderSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecter à ce serveur.
        /// </summary>
        public static string ConnectToThisServer {
            get {
                return ResourceManager.GetString("ConnectToThisServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecteur réseau: O.
        /// </summary>
        public static string DriveO {
            get {
                return ResourceManager.GetString("DriveO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir un serveur avant de soumettre la requête!.
        /// </summary>
        public static string message1 {
            get {
                return ResourceManager.GetString("message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de fichier batch réussi! Cliquez sur le fichier pour l&apos;exécuter.
        /// </summary>
        public static string message2 {
            get {
                return ResourceManager.GetString("message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le serveur choisi ne peut exécuter la requête!.
        /// </summary>
        public static string message3 {
            get {
                return ResourceManager.GetString("message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La création de fichier batch a échoué!.
        /// </summary>
        public static string message3a {
            get {
                return ResourceManager.GetString("message3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette étape consiste à faire correspondre au lecteur O:\ de votre Explorateur Windows un serveur de fichiers de
        /// projets que vous sélectionnerez dans TT Projet + .  Lorsque vous allez cliquer sur le bouton &quot;Connecter à ce serveur&quot;, vous verrez alors apparaître une boîte de dialogue de téléchargement de Windows. Lorsque cette boîte de dialogue apparaît, cliquez toujours sur le bouton Exécuter. Vous verrez alors un script s’exécuter en fenêtre de commande..
        /// </summary>
        public static string message4 {
            get {
                return ResourceManager.GetString("message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir un serveur....
        /// </summary>
        public static string message5 {
            get {
                return ResourceManager.GetString("message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voici la liste des serveurs de projets qui sont disponibles. Cliquez sur le bouton.
        /// </summary>
        public static string msgListeServeurs1 {
            get {
                return ResourceManager.GetString("msgListeServeurs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to afin de copier le lien vers le serveur, puis cliquez sur la touche Windows + E de votre clavier et coller le contenu du presse-papier dans la barre d&apos;adresse..
        /// </summary>
        public static string msgListeServeurs2 {
            get {
                return ResourceManager.GetString("msgListeServeurs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : Pour que la connection s&apos;effectue, vous devrez exécuter le fichier qui vous sera envoyé a cet effet..
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ requis.
        /// </summary>
        public static string requiredField {
            get {
                return ResourceManager.GetString("requiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveur.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ requis.
        /// </summary>
        public static string ServerNumberError {
            get {
                return ResourceManager.GetString("ServerNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette étape consiste à faire correspondre au lecteur W:\ ou S:\ de votre Explorateur Windows un serveur de fichiers de
        ///                                    projets que vous sélectionnerez dans TT Projet + .  Lorsque vous allez cliquer sur le bouton &quot;Connecter à ce serveur&quot;, vous verrez alors apparaître une boîte de dialogue de téléchargement de Windows. Lorsque cette boîte de dialogue apparaît, cliquez toujours sur le bouton Exécuter. Vous verrez alors un script s’exécuter en fenêtre de commande..
        /// </summary>
        public static string specialDrive {
            get {
                return ResourceManager.GetString("specialDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copie le chemin du répertoire de projet.
        /// </summary>
        public static string strMessage1 {
            get {
                return ResourceManager.GetString("strMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur ce bouton, puis sur la touche Windows + E de votre clavier et coller le contenu du presse-papier dans la barre d&apos;adresse.
        /// </summary>
        public static string strMessage2 {
            get {
                return ResourceManager.GetString("strMessage2", resourceCulture);
            }
        }
    }
}
