//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Views.Boomerang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class fiche {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fiche() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TetraTech.TTProjetPlus.Views.Boomerang.fiche", typeof(fiche).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string accueil {
            get {
                return ResourceManager.GetString("accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bureau.
        /// </summary>
        public static string agence {
            get {
                return ResourceManager.GetString("agence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        public static string aide {
            get {
                return ResourceManager.GetString("aide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût final Aménag. ext..
        /// </summary>
        public static string amenagmtFin {
            get {
                return ResourceManager.GetString("amenagmtFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. finaux Amnénag. ext..
        /// </summary>
        public static string amenagmtFinFees {
            get {
                return ResourceManager.GetString("amenagmtFinFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût prévu Aménag. ext..
        /// </summary>
        public static string amenagmtPrev {
            get {
                return ResourceManager.GetString("amenagmtPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. prévus Amnénag. ext..
        /// </summary>
        public static string amenagmtPrevFees {
            get {
                return ResourceManager.GetString("amenagmtPrevFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide financière respectée.
        /// </summary>
        public static string appui {
            get {
                return ResourceManager.GetString("appui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide projetée.
        /// </summary>
        public static string appuiPrevu {
            get {
                return ResourceManager.GetString("appuiPrevu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide réelle.
        /// </summary>
        public static string appuiReel {
            get {
                return ResourceManager.GetString("appuiReel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Architecte(s).
        /// </summary>
        public static string archi {
            get {
                return ResourceManager.GetString("archi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Final Other costs.
        /// </summary>
        public static string autreFin {
            get {
                return ResourceManager.GetString("autreFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Final Other fees.
        /// </summary>
        public static string autreFinFees {
            get {
                return ResourceManager.GetString("autreFinFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Estimated Other costs.
        /// </summary>
        public static string autrePrev {
            get {
                return ResourceManager.GetString("autrePrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Estimated Other fees.
        /// </summary>
        public static string autrePrevFees {
            get {
                return ResourceManager.GetString("autrePrevFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to par.
        /// </summary>
        public static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directeur de projet.
        /// </summary>
        public static string chargeAff {
            get {
                return ResourceManager.GetString("chargeAff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changement par Tetra Tech.
        /// </summary>
        public static string chgmtBpr {
            get {
                return ResourceManager.GetString("chgmtBpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changement par le client.
        /// </summary>
        public static string chgmtClient {
            get {
                return ResourceManager.GetString("chgmtClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les chiffres.
        /// </summary>
        public static string chiffres {
            get {
                return ResourceManager.GetString("chiffres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Client.
        /// </summary>
        public static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Numéro de projet.
        /// </summary>
        public static string codeAff {
            get {
                return ResourceManager.GetString("codeAff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conception.
        /// </summary>
        public static string conception {
            get {
                return ResourceManager.GetString("conception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Opérateur.
        /// </summary>
        public static string conducteur {
            get {
                return ResourceManager.GetString("conducteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentiel.
        /// </summary>
        public static string confidentiel {
            get {
                return ResourceManager.GetString("confidentiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Conso. du bâtiment.
        /// </summary>
        public static string consoBat {
            get {
                return ResourceManager.GetString("consoBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction.
        /// </summary>
        public static string construct {
            get {
                return ResourceManager.GetString("construct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût.
        /// </summary>
        public static string cout {
            get {
                return ResourceManager.GetString("cout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût final.
        /// </summary>
        public static string coutFin {
            get {
                return ResourceManager.GetString("coutFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coût global du projet.
        /// </summary>
        public static string coutGlob {
            get {
                return ResourceManager.GetString("coutGlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût prévu.
        /// </summary>
        public static string coutPrev {
            get {
                return ResourceManager.GetString("coutPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Fiche créée.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Fiche créée le.
        /// </summary>
        public static string createThe {
            get {
                return ResourceManager.GetString("createThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une fiche.
        /// </summary>
        public static string creation_fiche {
            get {
                return ResourceManager.GetString("creation_fiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates finales.
        /// </summary>
        public static string dateFinale {
            get {
                return ResourceManager.GetString("dateFinale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dates finales.
        /// </summary>
        public static string dateFinales {
            get {
                return ResourceManager.GetString("dateFinales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates prévues.
        /// </summary>
        public static string datePrevue {
            get {
                return ResourceManager.GetString("datePrevue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dates prévues.
        /// </summary>
        public static string datePrevues {
            get {
                return ResourceManager.GetString("datePrevues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string devise {
            get {
                return ResourceManager.GetString("devise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée du projet.
        /// </summary>
        public static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raisons de l&apos;écart.
        /// </summary>
        public static string ecartReal {
            get {
                return ResourceManager.GetString("ecartReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échéancier.
        /// </summary>
        public static string echeancier {
            get {
                return ResourceManager.GetString("echeancier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Economie d&apos;énergie.
        /// </summary>
        public static string ecoEnerg {
            get {
                return ResourceManager.GetString("ecoEnerg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Economie d&apos;énergie et période de retour sur investissements.
        /// </summary>
        public static string ecoEnergie {
            get {
                return ResourceManager.GetString("ecoEnergie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Economies monétaires.
        /// </summary>
        public static string ecoMonet {
            get {
                return ResourceManager.GetString("ecoMonet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût final électricité.
        /// </summary>
        public static string electFin {
            get {
                return ResourceManager.GetString("electFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. finaux électricité.
        /// </summary>
        public static string electFinFees {
            get {
                return ResourceManager.GetString("electFinFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût prévu électricité.
        /// </summary>
        public static string electPrev {
            get {
                return ResourceManager.GetString("electPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. prévus électricité.
        /// </summary>
        public static string electPrevFees {
            get {
                return ResourceManager.GetString("electPrevFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Electricité.
        /// </summary>
        public static string electricite {
            get {
                return ResourceManager.GetString("electricite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Equipe interne.
        /// </summary>
        public static string equipeInterne {
            get {
                return ResourceManager.GetString("equipeInterne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Honoraire Tetra Tech.
        /// </summary>
        public static string feesBpr {
            get {
                return ResourceManager.GetString("feesBpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. finaux.
        /// </summary>
        public static string feesFin {
            get {
                return ResourceManager.GetString("feesFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. prévus .
        /// </summary>
        public static string feesPrev {
            get {
                return ResourceManager.GetString("feesPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Honoraire de l&apos;équipe.
        /// </summary>
        public static string feesTeam {
            get {
                return ResourceManager.GetString("feesTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  final.
        /// </summary>
        public static string final {
            get {
                return ResourceManager.GetString("final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Finaux.
        /// </summary>
        public static string Finaux {
            get {
                return ResourceManager.GetString("Finaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Générer OPQIBI.
        /// </summary>
        public static string genOpqibi {
            get {
                return ResourceManager.GetString("genOpqibi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût final Gestion de projet.
        /// </summary>
        public static string gestFin {
            get {
                return ResourceManager.GetString("gestFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. finaux Gestion de projet.
        /// </summary>
        public static string gestFinFees {
            get {
                return ResourceManager.GetString("gestFinFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gestion de projet.
        /// </summary>
        public static string gestion {
            get {
                return ResourceManager.GetString("gestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût prévu Gestion de projet.
        /// </summary>
        public static string gestPrev {
            get {
                return ResourceManager.GetString("gestPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. prévus Gestion de projet.
        /// </summary>
        public static string gestPrevFees {
            get {
                return ResourceManager.GetString("gestPrevFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page d&apos;aide.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon..
        /// </summary>
        public static string hon {
            get {
                return ResourceManager.GetString("hon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Honoraires.
        /// </summary>
        public static string honoraire {
            get {
                return ResourceManager.GetString("honoraire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        public static string impr {
            get {
                return ResourceManager.GetString("impr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Informations internes.
        /// </summary>
        public static string infoInterne {
            get {
                return ResourceManager.GetString("infoInterne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût final Infrastructure.
        /// </summary>
        public static string infraFin {
            get {
                return ResourceManager.GetString("infraFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. finaux Infrastructure.
        /// </summary>
        public static string infraFinFees {
            get {
                return ResourceManager.GetString("infraFinFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût prévu Infrastructure.
        /// </summary>
        public static string infraPrev {
            get {
                return ResourceManager.GetString("infraPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. prévus Infrastructure.
        /// </summary>
        public static string infraPrevFees {
            get {
                return ResourceManager.GetString("infraPrevFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Infrastructure.
        /// </summary>
        public static string infrastructure {
            get {
                return ResourceManager.GetString("infrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dernière modification le.
        /// </summary>
        public static string lastMod {
            get {
                return ResourceManager.GetString("lastMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût final Mécanique.
        /// </summary>
        public static string mecaFin {
            get {
                return ResourceManager.GetString("mecaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. finaux Mécanique.
        /// </summary>
        public static string mecaFinFees {
            get {
                return ResourceManager.GetString("mecaFinFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mécanique.
        /// </summary>
        public static string mecanique {
            get {
                return ResourceManager.GetString("mecanique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût prévu Mécanique.
        /// </summary>
        public static string mecaPrev {
            get {
                return ResourceManager.GetString("mecaPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. prévus Mécanique.
        /// </summary>
        public static string mecaPrevFees {
            get {
                return ResourceManager.GetString("mecaPrevFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Plan de mesurage des économies.
        /// </summary>
        public static string mesurageEco {
            get {
                return ResourceManager.GetString("mesurageEco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        public static string mission {
            get {
                return ResourceManager.GetString("mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Montant.
        /// </summary>
        public static string montant {
            get {
                return ResourceManager.GetString("montant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation du projet.
        /// </summary>
        public static string montantEstim {
            get {
                return ResourceManager.GetString("montantEstim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Final.
        /// </summary>
        public static string montantFin {
            get {
                return ResourceManager.GetString("montantFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount tendered.
        /// </summary>
        public static string montantSoum {
            get {
                return ResourceManager.GetString("montantSoum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  mois.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mois.
        /// </summary>
        public static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes brouillons en cours ou en attente de validation.
        /// </summary>
        public static string myDrafts {
            get {
                return ResourceManager.GetString("myDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En effet, dés a présent, les fiches générées automatiquement en format PDF n&apos;afficheront plus de logo et présenteront uniquement le domaine et l&apos;expertise (bandeau bleu a gauche). Toutefois, vous avez encore la possibilitéd&apos;imposer le logo de votre choix en vous créant des &quot;paniers&quot;.&lt;br /&gt;&lt;br /&gt;&lt;b&gt;Mise a niveau des fiches de projet&lt;/b&gt;&lt;br /&gt;-Faire attention a la terminologie employée dans la description des projets afin de faire disparaitre le mot BPR.&lt;br /&gt;Par exemple, nous devrions lire : &quot;L&apos;équipe a réal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string newOnBoomerang {
            get {
                return ResourceManager.GetString("newOnBoomerang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nom du contact.
        /// </summary>
        public static string nomContact {
            get {
                return ResourceManager.GetString("nomContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non renseigné.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No structure (P-xxxxxx).
        /// </summary>
        public static string NoStructure {
            get {
                return ResourceManager.GetString("NoStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Numéro de référence projet du client.
        /// </summary>
        public static string numRef {
            get {
                return ResourceManager.GetString("numRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  de l&apos;équipe.
        /// </summary>
        public static string ofTeam {
            get {
                return ResourceManager.GetString("ofTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Organisme.
        /// </summary>
        public static string organisme {
            get {
                return ResourceManager.GetString("organisme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Autres partenaires.
        /// </summary>
        public static string others {
            get {
                return ResourceManager.GetString("others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes paniers.
        /// </summary>
        public static string paniers {
            get {
                return ResourceManager.GetString("paniers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particularités du projet.
        /// </summary>
        public static string particularite {
            get {
                return ResourceManager.GetString("particularite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photothéque.
        /// </summary>
        public static string phototheque {
            get {
                return ResourceManager.GetString("phototheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans et devis.
        /// </summary>
        public static string planDevis {
            get {
                return ResourceManager.GetString("planDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  prévu.
        /// </summary>
        public static string prevu {
            get {
                return ResourceManager.GetString("prevu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Prévue.
        /// </summary>
        public static string prevue {
            get {
                return ResourceManager.GetString("prevue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Prévues.
        /// </summary>
        public static string prevues {
            get {
                return ResourceManager.GetString("prevues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Prévus.
        /// </summary>
        public static string Prevus {
            get {
                return ResourceManager.GetString("Prevus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  PRI simple annuel.
        /// </summary>
        public static string pri {
            get {
                return ResourceManager.GetString("pri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiches projet.
        /// </summary>
        public static string projectSheet {
            get {
                return ResourceManager.GetString("projectSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Propriétaire de l&apos;ouvrage.
        /// </summary>
        public static string proprio {
            get {
                return ResourceManager.GetString("proprio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        public static string recherche {
            get {
                return ResourceManager.GetString("recherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Réelle.
        /// </summary>
        public static string reelle {
            get {
                return ResourceManager.GetString("reelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Réelles.
        /// </summary>
        public static string reelles {
            get {
                return ResourceManager.GetString("reelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  de réalisation.
        /// </summary>
        public static string resil {
            get {
                return ResourceManager.GetString("resil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature des travaux.
        /// </summary>
        public static string serviceEnvironnement {
            get {
                return ResourceManager.GetString("serviceEnvironnement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &amp;nbsp; |   &amp;nbsp;  .
        /// </summary>
        public static string space {
            get {
                return ResourceManager.GetString("space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût final Structure.
        /// </summary>
        public static string structFin {
            get {
                return ResourceManager.GetString("structFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. finaux Structure.
        /// </summary>
        public static string structFinFees {
            get {
                return ResourceManager.GetString("structFinFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coût prévu Structure.
        /// </summary>
        public static string structPrev {
            get {
                return ResourceManager.GetString("structPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hon. prévus Structure.
        /// </summary>
        public static string structPrevFees {
            get {
                return ResourceManager.GetString("structPrevFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Structure.
        /// </summary>
        public static string structure {
            get {
                return ResourceManager.GetString("structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  L&apos;équipe.
        /// </summary>
        public static string theTeam {
            get {
                return ResourceManager.GetString("theTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Après travaux.
        /// </summary>
        public static string travauxApres {
            get {
                return ResourceManager.GetString("travauxApres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Avant travaux.
        /// </summary>
        public static string travauxAvant {
            get {
                return ResourceManager.GetString("travauxAvant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;accès au contenu de cette fiche est a été restreint par le responsable de Boomerang.
        /// </summary>
        public static string txtConfidentiel {
            get {
                return ResourceManager.GetString("txtConfidentiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Type de client.
        /// </summary>
        public static string typeClient {
            get {
                return ResourceManager.GetString("typeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité.
        /// </summary>
        public static string unite {
            get {
                return ResourceManager.GetString("unite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Année.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Période de réalisation.
        /// </summary>
        public static string yearReal {
            get {
                return ResourceManager.GetString("yearReal", resourceCulture);
            }
        }
    }
}
