//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Views.ArchiveProjet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArchiveProjetRessource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArchiveProjetRessource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TetraTech.TTProjetPlus.Views.ArchiveProjet.ArchiveProjetRessource", typeof(ArchiveProjetRessource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;action a été annulée..
        /// </summary>
        public static string ActionCancelled {
            get {
                return ResourceManager.GetString("ActionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avancé.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiver.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez confirmer l&apos;archivage de ce projet. Cette opération est irréversible..
        /// </summary>
        public static string ArchiveConfirm {
            get {
                return ResourceManager.GetString("ArchiveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de l&apos;archivage du projet.Veuillez communiquer avec l&apos;administrateur..
        /// </summary>
        public static string ArchiveError {
            get {
                return ResourceManager.GetString("ArchiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet demandé n&apos;a pu être déplacé vers l&apos;archive. Pour plus de détails, veuillez communiquer avec l&apos;administrateur..
        /// </summary>
        public static string ArchiveNotMoved {
            get {
                return ResourceManager.GetString("ArchiveNotMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiver un projet.
        /// </summary>
        public static string ArchiveProject {
            get {
                return ResourceManager.GetString("ArchiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiver plusieurs projets.
        /// </summary>
        public static string ArchiveProject1 {
            get {
                return ResourceManager.GetString("ArchiveProject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;archivage s&apos;est effectué avec succès. La page sera rafraîchie afin de mettre à jour la liste des projets..
        /// </summary>
        public static string ArchiveSuccess {
            get {
                return ResourceManager.GetString("ArchiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir un projet....
        /// </summary>
        public static string ChooseProject {
            get {
                return ResourceManager.GetString("ChooseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir un projet avant de soumettre la requête!.
        /// </summary>
        public static string ErrorChooseProject {
            get {
                return ResourceManager.GetString("ErrorChooseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet demandé n&apos;existe pas sur le serveur. Pour plus de détails, veuillez communiquer avec l&apos;administrateur..
        /// </summary>
        public static string NotExistingProject {
            get {
                return ResourceManager.GetString("NotExistingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option(s) choisie(s).
        /// </summary>
        public static string optionChoosen {
            get {
                return ResourceManager.GetString("optionChoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                         Windows Explorer ou une autre application pointe vers la structure de répertoires demandée..
        /// </summary>
        public static string RepStrucInUse {
            get {
                return ResourceManager.GetString("RepStrucInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès restreint. Veuillez contacter l&apos;administrateur pour gérer l&apos;accès à cette fonctionnalité..
        /// </summary>
        public static string RestrictedAccess {
            get {
                return ResourceManager.GetString("RestrictedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveur utilisé:.
        /// </summary>
        public static string ServerUsed {
            get {
                return ResourceManager.GetString("ServerUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;archivage du projet n&apos;est pas possible tant que la structure de répertoires est utilisée..
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
    }
}
