//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Views.InfoProjet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfoProjectRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoProjectRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TetraTech.TTProjetPlus.Views.InfoProjet.InfoProjectRessources", typeof(InfoProjectRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepter.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerte.
        /// </summary>
        public static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas indiqué de critères de recherche, donc la recherche pourrait prendre un certain délai.  Pour confirmer, cliquez &quot;Poursuivre&quot;..
        /// </summary>
        public static string alertMessage {
            get {
                return ResourceManager.GetString("alertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La recherche de projets ayant le statut &quot;Ancien projet Great Plains&quot; pourrait prendre un certain délai. Il est conseillé d&apos;ajouter un autre critère de recherche tel que: Numéro de projet Description No client Nom client Numéro attribué le &lt;br&gt;Pour confirmer, cliquez &quot;Poursuivre&quot;..
        /// </summary>
        public static string alertMessage2 {
            get {
                return ResourceManager.GetString("alertMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La structure de répertoires du projet n&apos;est plus sur le réseau..
        /// </summary>
        public static string alertMessage3 {
            get {
                return ResourceManager.GetString("alertMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez consulter le site web des archives &quot;TT Index (Archives)&quot;: http://archivestqc.tetratech.com:1100.
        /// </summary>
        public static string alertMessage4 {
            get {
                return ResourceManager.GetString("alertMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://archivestqc.tetratech.com:1100.
        /// </summary>
        public static string alertMessage5 {
            get {
                return ResourceManager.GetString("alertMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant approximatif.
        /// </summary>
        public static string ApproximateAmount {
            get {
                return ResourceManager.GetString("ApproximateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;archivage GP.
        /// </summary>
        public static string archiveDate {
            get {
                return ResourceManager.GetString("archiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent de facturation.
        /// </summary>
        public static string BillingAgent {
            get {
                return ResourceManager.GetString("BillingAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez des modifications en cours. Si vous quittez la page le modifications ne seront pas enregistrées..
        /// </summary>
        public static string btnConfirmLeave {
            get {
                return ResourceManager.GetString("btnConfirmLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité d&apos;affaires.
        /// </summary>
        public static string BusinessUnit {
            get {
                return ResourceManager.GetString("BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur &quot;Critères de recherche&quot; pour diminuer ou visualiser cette section.
        /// </summary>
        public static string click {
            get {
                return ResourceManager.GetString("click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du client.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro du client.
        /// </summary>
        public static string ClientNumber {
            get {
                return ResourceManager.GetString("ClientNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de Phase.
        /// </summary>
        public static string CodePhase {
            get {
                return ResourceManager.GetString("CodePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaires.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compagnie.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact client.
        /// </summary>
        public static string ContactClient {
            get {
                return ResourceManager.GetString("ContactClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poursuivre.
        /// </summary>
        public static string continueA {
            get {
                return ResourceManager.GetString("continueA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controleur de coût.
        /// </summary>
        public static string ContractAdministratorLabel {
            get {
                return ResourceManager.GetString("ContractAdministratorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No de contrat / bon de commande.
        /// </summary>
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de contrat.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir en projet.
        /// </summary>
        public static string ConvertToProject {
            get {
                return ResourceManager.GetString("ConvertToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copie le chemin du répertoire de projet.
        /// </summary>
        public static string CopyPath {
            get {
                return ResourceManager.GetString("CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur ce bouton, puis sur la touche Windows + E de votre clavier et coller le contenu du presse-papier dans la barre d&apos;adresse.
        /// </summary>
        public static string CopyPath2 {
            get {
                return ResourceManager.GetString("CopyPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour ouvrir un répertoire de projet.
        /// </summary>
        public static string CopyPath3 {
            get {
                return ResourceManager.GetString("CopyPath3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur le bouton qui se retrouve dans la colonne &quot;Chemin du répertoire de projet&quot; puis sur la touche Windows + E de votre clavier et coller le contenu du presse-papier dans la barre d&apos;adresse.
        /// </summary>
        public static string CopyPath4 {
            get {
                return ResourceManager.GetString("CopyPath4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et coller le contenu du presse-papier dans la barre d&apos;adresse.
        /// </summary>
        public static string CopyPath5 {
            get {
                return ResourceManager.GetString("CopyPath5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Descritption {
            get {
                return ResourceManager.GetString("Descritption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails/Édition.
        /// </summary>
        public static string DetailsE {
            get {
                return ResourceManager.GetString("DetailsE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string doc {
            get {
                return ResourceManager.GetString("doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de report de documentation.
        /// </summary>
        public static string DocPostponedDate {
            get {
                return ResourceManager.GetString("DocPostponedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éditer.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse courriel.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse courriel d&apos;envoie de la facture (si envoie électronique).
        /// </summary>
        public static string EmailAdressIf {
            get {
                return ResourceManager.GetString("EmailAdressIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous le document Excel d&apos;overture de projet.
        /// </summary>
        public static string ExcelDocRequest {
            get {
                return ResourceManager.GetString("ExcelDocRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de facturation.
        /// </summary>
        public static string FacturationAddress {
            get {
                return ResourceManager.GetString("FacturationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente de facturation.
        /// </summary>
        public static string FacturationAgent {
            get {
                return ResourceManager.GetString("FacturationAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client final.
        /// </summary>
        public static string FinalClient {
            get {
                return ResourceManager.GetString("FinalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations générales.
        /// </summary>
        public static string generalInfotmation {
            get {
                return ResourceManager.GetString("generalInfotmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclure les projets fermés.
        /// </summary>
        public static string includeClosed {
            get {
                return ResourceManager.GetString("includeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info-Projet.
        /// </summary>
        public static string InfoProjet {
            get {
                return ResourceManager.GetString("InfoProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initié par.
        /// </summary>
        public static string InitiatedBy {
            get {
                return ResourceManager.GetString("InitiatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initié par (OS).
        /// </summary>
        public static string InitiatedByOS {
            get {
                return ResourceManager.GetString("InitiatedByOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initié par (projet).
        /// </summary>
        public static string InitiatedByProject {
            get {
                return ResourceManager.GetString("InitiatedByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projets par page.
        /// </summary>
        public static string ItemsPerPage {
            get {
                return ResourceManager.GetString("ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet lié ou projet maitre.
        /// </summary>
        public static string MasterOrlinkedProject {
            get {
                return ResourceManager.GetString("MasterOrlinkedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet maitre.
        /// </summary>
        public static string MasterProject {
            get {
                return ResourceManager.GetString("MasterProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle du répertoire de projet.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun projet n&apos;est rattaché à votre numéro d&apos;employé..
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun résultat pour cette requête....
        /// </summary>
        public static string noResultForThisQuery {
            get {
                return ResourceManager.GetString("noResultForThisQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bureau.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse du bureau (facture).
        /// </summary>
        public static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancien nom du client GP.
        /// </summary>
        public static string OldClientNameGP {
            get {
                return ResourceManager.GetString("OldClientNameGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancien numéro du client GP.
        /// </summary>
        public static string OldClientNumberGP {
            get {
                return ResourceManager.GetString("OldClientNumberGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;ouverture du projet.
        /// </summary>
        public static string OpeningDate {
            get {
                return ResourceManager.GetString("OpeningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir:.
        /// </summary>
        public static string OpenPath {
            get {
                return ResourceManager.GetString("OpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options choisies.
        /// </summary>
        public static string optionChoosen {
            get {
                return ResourceManager.GetString("optionChoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation (valeur grisée si inactive dans TLX).
        /// </summary>
        public static string ORG {
            get {
                return ResourceManager.GetString("ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string ORGList {
            get {
                return ResourceManager.GetString("ORGList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} de {2} projets.
        /// </summary>
        public static string PageableDisplay {
            get {
                return ResourceManager.GetString("PageableDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin du répertoire de projet.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derniére mise à jour des données.
        /// </summary>
        public static string PeriodWeekDate {
            get {
                return ResourceManager.GetString("PeriodWeekDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionnaire de programme.
        /// </summary>
        public static string ProgramManager {
            get {
                return ResourceManager.GetString("ProgramManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directeur de projet.
        /// </summary>
        public static string ProgramMgrLabel {
            get {
                return ResourceManager.GetString("ProgramMgrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin du projet.
        /// </summary>
        public static string ProjectEndDate {
            get {
                return ResourceManager.GetString("ProjectEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionnaire de projet.
        /// </summary>
        public static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionnaire de projet.
        /// </summary>
        public static string ProjectMgrLabel {
            get {
                return ResourceManager.GetString("ProjectMgrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de projet.
        /// </summary>
        public static string projectNumber {
            get {
                return ResourceManager.GetString("projectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de début du projet.
        /// </summary>
        public static string ProjectStartDate {
            get {
                return ResourceManager.GetString("ProjectStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de Projet.
        /// </summary>
        public static string RAFAction {
            get {
                return ResourceManager.GetString("RAFAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réferences et commentaires.
        /// </summary>
        public static string RefAndComments {
            get {
                return ResourceManager.GetString("RefAndComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        public static string reinitialize {
            get {
                return ResourceManager.GetString("reinitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de report.
        /// </summary>
        public static string reportDate {
            get {
                return ResourceManager.GetString("reportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critères de recherche.
        /// </summary>
        public static string searchCriteria {
            get {
                return ResourceManager.GetString("searchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chercher dans.
        /// </summary>
        public static string SearchIn {
            get {
                return ResourceManager.GetString("SearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultats de la recherche.
        /// </summary>
        public static string searchResults {
            get {
                return ResourceManager.GetString("searchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel EN.
        /// </summary>
        public static string sendMailEN {
            get {
                return ResourceManager.GetString("sendMailEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel FR.
        /// </summary>
        public static string sendMailFR {
            get {
                return ResourceManager.GetString("sendMailFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin de partage.
        /// </summary>
        public static string sharePath {
            get {
                return ResourceManager.GetString("sharePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse d&apos;expedition.
        /// </summary>
        public static string ShippingAddress {
            get {
                return ResourceManager.GetString("ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut de la documentation.
        /// </summary>
        public static string StatusDoc {
            get {
                return ResourceManager.GetString("StatusDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro attribué le.
        /// </summary>
        public static string submittedDate {
            get {
                return ResourceManager.GetString("submittedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astuces.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projets.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre du projet.
        /// </summary>
        public static string TitleOS {
            get {
                return ResourceManager.GetString("TitleOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planification - Analyse mandat.
        /// </summary>
        public static string TitlePlanification {
            get {
                return ResourceManager.GetString("TitlePlanification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre abrégé du projet.
        /// </summary>
        public static string TitleProjet {
            get {
                return ResourceManager.GetString("TitleProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie de travail(SF330).
        /// </summary>
        public static string WorkCategory {
            get {
                return ResourceManager.GetString("WorkCategory", resourceCulture);
            }
        }
    }
}
