//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Views.OpenProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OpenProjectRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenProjectRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TetraTech.TTProjetPlus.Views.OpenProject.OpenProjectRessources", typeof(OpenProjectRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une tâche.
        /// </summary>
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joindre à la facture.
        /// </summary>
        public static string addToBill {
            get {
                return ResourceManager.GetString("addToBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandé par.
        /// </summary>
        public static string askedBy {
            get {
                return ResourceManager.GetString("askedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de facturation.
        /// </summary>
        public static string billingAddress {
            get {
                return ResourceManager.GetString("billingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent de facturation.
        /// </summary>
        public static string billingAgent {
            get {
                return ResourceManager.GetString("billingAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget de coûts.
        /// </summary>
        public static string budegtCost {
            get {
                return ResourceManager.GetString("budegtCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir une option:.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string classification {
            get {
                return ResourceManager.GetString("classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification à ajouter selon le contrat et spécifications du contrat.
        /// </summary>
        public static string classificationContract {
            get {
                return ResourceManager.GetString("classificationContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approbation du client.
        /// </summary>
        public static string clientApproval {
            get {
                return ResourceManager.GetString("clientApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification du client.
        /// </summary>
        public static string clientIdentification {
            get {
                return ResourceManager.GetString("clientIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des clients.
        /// </summary>
        public static string clientList {
            get {
                return ResourceManager.GetString("clientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapetisser.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consortium.
        /// </summary>
        public static string consortium {
            get {
                return ResourceManager.GetString("consortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de contrat.
        /// </summary>
        public static string contractType {
            get {
                return ResourceManager.GetString("contractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir une offre en projet.
        /// </summary>
        public static string convertOSToProject {
            get {
                return ResourceManager.GetString("convertOSToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un autre client.
        /// </summary>
        public static string createNewClient {
            get {
                return ResourceManager.GetString("createNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une nouvelle version.
        /// </summary>
        public static string createNewVersion {
            get {
                return ResourceManager.GetString("createNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du client.
        /// </summary>
        public static string customerName {
            get {
                return ResourceManager.GetString("customerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # du client.
        /// </summary>
        public static string customerNumber {
            get {
                return ResourceManager.GetString("customerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (AAAA-MM-JJ).
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionnaire de programme (Dir. de projet).
        /// </summary>
        public static string dirProject {
            get {
                return ResourceManager.GetString("dirProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Électronique.
        /// </summary>
        public static string electronic {
            get {
                return ResourceManager.GetString("electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse courriel.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin du projet estimée.
        /// </summary>
        public static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étendre.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport de dépenses original.
        /// </summary>
        public static string ExpenseReportOriginal {
            get {
                return ResourceManager.GetString("ExpenseReportOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport de frais.
        /// </summary>
        public static string expenses {
            get {
                return ResourceManager.GetString("expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client final.
        /// </summary>
        public static string finalClient {
            get {
                return ResourceManager.GetString("finalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionnaire du projet (chargé de projet).
        /// </summary>
        public static string gestProjet {
            get {
                return ResourceManager.GetString("gestProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Méthode de calcul de revenu.
        /// </summary>
        public static string incomeCalculationMet {
            get {
                return ResourceManager.GetString("incomeCalculationMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter-compagnie.
        /// </summary>
        public static string interCompany {
            get {
                return ResourceManager.GetString("interCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture fournisseur originale.
        /// </summary>
        public static string InvoiceSupplierOriginal {
            get {
                return ResourceManager.GetString("InvoiceSupplierOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture fournisseurs.
        /// </summary>
        public static string invoiceSuppliers {
            get {
                return ResourceManager.GetString("invoiceSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langues des communcations.
        /// </summary>
        public static string langagesCom {
            get {
                return ResourceManager.GetString("langagesCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre complet.
        /// </summary>
        public static string longTitle {
            get {
                return ResourceManager.GetString("longTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation du mandat.
        /// </summary>
        public static string mandatLocalisation {
            get {
                return ResourceManager.GetString("mandatLocalisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaire obligatoire sur la feuille de temps.
        /// </summary>
        public static string MandatoryTimesheetComment {
            get {
                return ResourceManager.GetString("MandatoryTimesheetComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divers.
        /// </summary>
        public static string miscellaneous {
            get {
                return ResourceManager.GetString("miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple clients.
        /// </summary>
        public static string multipleClient {
            get {
                return ResourceManager.GetString("multipleClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple bons de commande.
        /// </summary>
        public static string multipleOrder {
            get {
                return ResourceManager.GetString("multipleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doit apparaître sur la facture.
        /// </summary>
        public static string MustAppearOnBill {
            get {
                return ResourceManager.GetString("MustAppearOnBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune (un TAR est exigé).
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de résultat.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de bureau (apparaîtra sur le contrat).
        /// </summary>
        public static string officeAddress {
            get {
                return ResourceManager.GetString("officeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;ouverture Tlinx.
        /// </summary>
        public static string openDate {
            get {
                return ResourceManager.GetString("openDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation (revenu).
        /// </summary>
        public static string Org_income {
            get {
                return ResourceManager.GetString("Org_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listes des offres de service.
        /// </summary>
        public static string OSList {
            get {
                return ResourceManager.GetString("OSList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre gestionnaire (si nécessaire).
        /// </summary>
        public static string otherGest {
            get {
                return ResourceManager.GetString("otherGest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre membre clé  No 1.
        /// </summary>
        public static string otherKM1 {
            get {
                return ResourceManager.GetString("otherKM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre membre clé  No 2.
        /// </summary>
        public static string otherKM2 {
            get {
                return ResourceManager.GetString("otherKM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papier.
        /// </summary>
        public static string paper {
            get {
                return ResourceManager.GetString("paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préférences des communications.
        /// </summary>
        public static string preferedCom {
            get {
                return ResourceManager.GetString("preferedCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des projets.
        /// </summary>
        public static string PRlist {
            get {
                return ResourceManager.GetString("PRlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme (type de projet).
        /// </summary>
        public static string programType {
            get {
                return ResourceManager.GetString("programType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification du projet et des membres clés.
        /// </summary>
        public static string projectIdentification {
            get {
                return ResourceManager.GetString("projectIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de projet.
        /// </summary>
        public static string ProjectNumber {
            get {
                return ResourceManager.GetString("ProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouverture du projet.
        /// </summary>
        public static string projectOpening {
            get {
                return ResourceManager.GetString("projectOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Références(s) client (bon de commande, contrat, avenant, etc.).
        /// </summary>
        public static string refCustomer {
            get {
                return ResourceManager.GetString("refCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la personne responsable.
        /// </summary>
        public static string responsibleName {
            get {
                return ResourceManager.GetString("responsibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone de la personne responsable.
        /// </summary>
        public static string responsiblePhone {
            get {
                return ResourceManager.GetString("responsiblePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse d&apos;expedition (lieu des travaux).
        /// </summary>
        public static string shippingAddress {
            get {
                return ResourceManager.GetString("shippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre abrégé (unique).
        /// </summary>
        public static string shortTitle {
            get {
                return ResourceManager.GetString("shortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soumettre.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAR.
        /// </summary>
        public static string TAR {
            get {
                return ResourceManager.GetString("TAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feuille de temps.
        /// </summary>
        public static string timeSheet {
            get {
                return ResourceManager.GetString("timeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaires obligatoires à la feuille de temps.
        /// </summary>
        public static string timeSheetComments {
            get {
                return ResourceManager.GetString("timeSheetComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbale (un TAR est exigé).
        /// </summary>
        public static string verbal {
            get {
                return ResourceManager.GetString("verbal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des versions.
        /// </summary>
        public static string versionsList {
            get {
                return ResourceManager.GetString("versionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie du travail.
        /// </summary>
        public static string workType {
            get {
                return ResourceManager.GetString("workType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Écrite.
        /// </summary>
        public static string written {
            get {
                return ResourceManager.GetString("written", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
