//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acct_Center
    {
        public int Acct_Center_ID { get; set; }
        public string Acct_Center1 { get; set; }
        public int Acct_Group_ID { get; set; }
        public bool isActive { get; set; }
    }
}
