//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssClient
    {
        public Nullable<long> rn { get; set; }
        public string Customer_Number { get; set; }
        public string Customer_Name { get; set; }
        public string GPCustID { get; set; }
        public string CUSTNAME { get; set; }
    }
}
