//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BPRProjetEntitiesNew : DbContext
    {
        public BPRProjetEntitiesNew()
            : base("name=BPRProjetEntitiesNew")
        {
            // Get the ObjectContext related to this DbContext
            var objectContext = (this as IObjectContextAdapter).ObjectContext;

            // Sets the command timeout for all the commands
            objectContext.CommandTimeout = 0;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<Etat_Projet> Etat_Projet { get; set; }
        public virtual DbSet<MapName> MapNames { get; set; }
        public virtual DbSet<Modele> Modeles { get; set; }
        public virtual DbSet<Modele_Securite> Modele_Securite { get; set; }
        public virtual DbSet<Modele_Selection> Modele_Selection { get; set; }
        public virtual DbSet<Modele_Selection_Repertoire> Modele_Selection_Repertoire { get; set; }
        public virtual DbSet<Projet> Projets { get; set; }
        public virtual DbSet<Projet_Exclusion> Projet_Exclusion { get; set; }
        public virtual DbSet<Projet_Exclusion_Securite> Projet_Exclusion_Securite { get; set; }
        public virtual DbSet<Projet_Repertoire> Projet_Repertoire { get; set; }
        public virtual DbSet<Projet_Repertoire_Verif> Projet_Repertoire_Verif { get; set; }
        public virtual DbSet<Repertoire_Securite> Repertoire_Securite { get; set; }
        public virtual DbSet<Repertoire_Securite_Groupe> Repertoire_Securite_Groupe { get; set; }
        public virtual DbSet<Security_Project_Exclusion> Security_Project_Exclusion { get; set; }
        public virtual DbSet<Serveur> Serveurs { get; set; }
        public virtual DbSet<SpecialMapServer> SpecialMapServers { get; set; }
        public virtual DbSet<C__KM> C__KM { get; set; }
        public virtual DbSet<C__PC> C__PC { get; set; }
        public virtual DbSet<C__tempKM> C__tempKM { get; set; }
        public virtual DbSet<ProjectLog> ProjectLogs { get; set; }
        public virtual DbSet<Repertoire_BIM> Repertoire_BIM { get; set; }
        public virtual DbSet<repertoire_pre_import> repertoire_pre_import { get; set; }
        public virtual DbSet<Securite_Groupe_Base> Securite_Groupe_Base { get; set; }
        public virtual DbSet<Security_ApplySecurityResult> Security_ApplySecurityResult { get; set; }
        public virtual DbSet<Security_FileToDo> Security_FileToDo { get; set; }
        public virtual DbSet<Security_List> Security_List { get; set; }
        public virtual DbSet<Security_Project_Inclusion> Security_Project_Inclusion { get; set; }
        public virtual DbSet<Security_Psexec_Output> Security_Psexec_Output { get; set; }
        public virtual DbSet<Security_Result> Security_Result { get; set; }
        public virtual DbSet<Security_Servers> Security_Servers { get; set; }
        public virtual DbSet<testRepertoire> testRepertoires { get; set; }
        public virtual DbSet<Security_Directory_Logs> Security_Directory_Logs { get; set; }
        public virtual DbSet<ListeDocDepotAutomatiqueTQE> ListeDocDepotAutomatiqueTQEs { get; set; }
        public virtual DbSet<TQEDocsToInsertInSubForlder> TQEDocsToInsertInSubForlders { get; set; }
        public virtual DbSet<TQEDocsToInsertInSubForlders_Sly> TQEDocsToInsertInSubForlders_Sly { get; set; }
        public virtual DbSet<Nasuni_TT_ProjectsToSecured> Nasuni_TT_ProjectsToSecured { get; set; }
        public virtual DbSet<Repertoire> Repertoires { get; set; }
        public virtual DbSet<Security_Project_Equivalence> Security_Project_Equivalence { get; set; }
        public virtual DbSet<tbl_ObtenirRepertoireParProjetTTProjetPlusNasuni> tbl_ObtenirRepertoireParProjetTTProjetPlusNasuni { get; set; }
    
        public virtual int f_debug_DeleteProjet(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_debug_DeleteProjet", idParameter);
        }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp007()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp007");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual ObjectResult<eusp_ObtenirRepertoire_Result> eusp_ObtenirRepertoire(Nullable<int> modeleId, Nullable<int> repertoireId)
        {
            var modeleIdParameter = modeleId.HasValue ?
                new ObjectParameter("ModeleId", modeleId) :
                new ObjectParameter("ModeleId", typeof(int));
    
            var repertoireIdParameter = repertoireId.HasValue ?
                new ObjectParameter("RepertoireId", repertoireId) :
                new ObjectParameter("RepertoireId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<eusp_ObtenirRepertoire_Result>("eusp_ObtenirRepertoire", modeleIdParameter, repertoireIdParameter);
        }
    
        public virtual ObjectResult<Get_MapServeur_Result> Get_MapServeur(Nullable<int> mapId, string lang)
        {
            var mapIdParameter = mapId.HasValue ?
                new ObjectParameter("MapId", mapId) :
                new ObjectParameter("MapId", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_MapServeur_Result>("Get_MapServeur", mapIdParameter, langParameter);
        }
    
        public virtual ObjectResult<Get_NewMapName_Result> Get_NewMapName(string lang)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_NewMapName_Result>("Get_NewMapName", langParameter);
        }
    
        public virtual int SP_UPDATE_REPERTOIRE_PRODUCTION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_REPERTOIRE_PRODUCTION");
        }
    
        public virtual int Tsp_prj_activity_child_list(string rep_parent, Nullable<int> mod_id, ObjectParameter activity_list_cursor)
        {
            var rep_parentParameter = rep_parent != null ?
                new ObjectParameter("Rep_parent", rep_parent) :
                new ObjectParameter("Rep_parent", typeof(string));
    
            var mod_idParameter = mod_id.HasValue ?
                new ObjectParameter("mod_id", mod_id) :
                new ObjectParameter("mod_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tsp_prj_activity_child_list", rep_parentParameter, mod_idParameter, activity_list_cursor);
        }
    
        public virtual int tsp_prj_activity_tree_build(string rep_parent, Nullable<int> mod_id, string gtemp_table_name, string indent_string)
        {
            var rep_parentParameter = rep_parent != null ?
                new ObjectParameter("Rep_parent", rep_parent) :
                new ObjectParameter("Rep_parent", typeof(string));
    
            var mod_idParameter = mod_id.HasValue ?
                new ObjectParameter("mod_id", mod_id) :
                new ObjectParameter("mod_id", typeof(int));
    
            var gtemp_table_nameParameter = gtemp_table_name != null ?
                new ObjectParameter("gtemp_table_name", gtemp_table_name) :
                new ObjectParameter("gtemp_table_name", typeof(string));
    
            var indent_stringParameter = indent_string != null ?
                new ObjectParameter("indent_string", indent_string) :
                new ObjectParameter("indent_string", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tsp_prj_activity_tree_build", rep_parentParameter, mod_idParameter, gtemp_table_nameParameter, indent_stringParameter);
        }
    
        public virtual int Tsp_prj_activity_tree_list(Nullable<int> mod_id, string pro_id)
        {
            var mod_idParameter = mod_id.HasValue ?
                new ObjectParameter("Mod_id", mod_id) :
                new ObjectParameter("Mod_id", typeof(int));
    
            var pro_idParameter = pro_id != null ?
                new ObjectParameter("Pro_id", pro_id) :
                new ObjectParameter("Pro_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tsp_prj_activity_tree_list", mod_idParameter, pro_idParameter);
        }
    
        public virtual int usp_AjouterModeleSelection(string utilisateurId, string nom, string description, Nullable<int> modeleID, ObjectParameter @return)
        {
            var utilisateurIdParameter = utilisateurId != null ?
                new ObjectParameter("UtilisateurId", utilisateurId) :
                new ObjectParameter("UtilisateurId", typeof(string));
    
            var nomParameter = nom != null ?
                new ObjectParameter("Nom", nom) :
                new ObjectParameter("Nom", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var modeleIDParameter = modeleID.HasValue ?
                new ObjectParameter("ModeleID", modeleID) :
                new ObjectParameter("ModeleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AjouterModeleSelection", utilisateurIdParameter, nomParameter, descriptionParameter, modeleIDParameter, @return);
        }
    
        public virtual int usp_AjouterModeleSelectionRepertoire(Nullable<int> modeleSelectionId, Nullable<int> repertoireId)
        {
            var modeleSelectionIdParameter = modeleSelectionId.HasValue ?
                new ObjectParameter("ModeleSelectionId", modeleSelectionId) :
                new ObjectParameter("ModeleSelectionId", typeof(int));
    
            var repertoireIdParameter = repertoireId.HasValue ?
                new ObjectParameter("RepertoireId", repertoireId) :
                new ObjectParameter("RepertoireId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AjouterModeleSelectionRepertoire", modeleSelectionIdParameter, repertoireIdParameter);
        }
    
        public virtual int usp_AjouterProjet(string projetID, Nullable<int> modeleSecuriteId, Nullable<int> serveurID, Nullable<int> typeProjet, string parent, string utilisateurId, Nullable<int> etatProjetID, Nullable<bool> isAdmin)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            var modeleSecuriteIdParameter = modeleSecuriteId.HasValue ?
                new ObjectParameter("ModeleSecuriteId", modeleSecuriteId) :
                new ObjectParameter("ModeleSecuriteId", typeof(int));
    
            var serveurIDParameter = serveurID.HasValue ?
                new ObjectParameter("ServeurID", serveurID) :
                new ObjectParameter("ServeurID", typeof(int));
    
            var typeProjetParameter = typeProjet.HasValue ?
                new ObjectParameter("TypeProjet", typeProjet) :
                new ObjectParameter("TypeProjet", typeof(int));
    
            var parentParameter = parent != null ?
                new ObjectParameter("Parent", parent) :
                new ObjectParameter("Parent", typeof(string));
    
            var utilisateurIdParameter = utilisateurId != null ?
                new ObjectParameter("UtilisateurId", utilisateurId) :
                new ObjectParameter("UtilisateurId", typeof(string));
    
            var etatProjetIDParameter = etatProjetID.HasValue ?
                new ObjectParameter("EtatProjetID", etatProjetID) :
                new ObjectParameter("EtatProjetID", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AjouterProjet", projetIDParameter, modeleSecuriteIdParameter, serveurIDParameter, typeProjetParameter, parentParameter, utilisateurIdParameter, etatProjetIDParameter, isAdminParameter);
        }
    
        public virtual int usp_AjouterProjet_bk_2016_03_16(string projetID, Nullable<int> modeleSecuriteId, Nullable<int> serveurID, Nullable<int> typeProjet, string parent, string utilisateurId, Nullable<int> etatProjetID)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            var modeleSecuriteIdParameter = modeleSecuriteId.HasValue ?
                new ObjectParameter("ModeleSecuriteId", modeleSecuriteId) :
                new ObjectParameter("ModeleSecuriteId", typeof(int));
    
            var serveurIDParameter = serveurID.HasValue ?
                new ObjectParameter("ServeurID", serveurID) :
                new ObjectParameter("ServeurID", typeof(int));
    
            var typeProjetParameter = typeProjet.HasValue ?
                new ObjectParameter("TypeProjet", typeProjet) :
                new ObjectParameter("TypeProjet", typeof(int));
    
            var parentParameter = parent != null ?
                new ObjectParameter("Parent", parent) :
                new ObjectParameter("Parent", typeof(string));
    
            var utilisateurIdParameter = utilisateurId != null ?
                new ObjectParameter("UtilisateurId", utilisateurId) :
                new ObjectParameter("UtilisateurId", typeof(string));
    
            var etatProjetIDParameter = etatProjetID.HasValue ?
                new ObjectParameter("EtatProjetID", etatProjetID) :
                new ObjectParameter("EtatProjetID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AjouterProjet_bk_2016_03_16", projetIDParameter, modeleSecuriteIdParameter, serveurIDParameter, typeProjetParameter, parentParameter, utilisateurIdParameter, etatProjetIDParameter);
        }
    
        public virtual int usp_AjouterProjetRepertoire(Nullable<int> repertoireId, string projetId)
        {
            var repertoireIdParameter = repertoireId.HasValue ?
                new ObjectParameter("RepertoireId", repertoireId) :
                new ObjectParameter("RepertoireId", typeof(int));
    
            var projetIdParameter = projetId != null ?
                new ObjectParameter("ProjetId", projetId) :
                new ObjectParameter("ProjetId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AjouterProjetRepertoire", repertoireIdParameter, projetIdParameter);
        }
    
        public virtual int usp_AjouterServeur(string nom, string iP, string description, string domaine, string compagnie, string startingPath, string impersonateUser, string remotePath, Nullable<int> mapperSeulement)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("Nom", nom) :
                new ObjectParameter("Nom", typeof(string));
    
            var iPParameter = iP != null ?
                new ObjectParameter("IP", iP) :
                new ObjectParameter("IP", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var domaineParameter = domaine != null ?
                new ObjectParameter("Domaine", domaine) :
                new ObjectParameter("Domaine", typeof(string));
    
            var compagnieParameter = compagnie != null ?
                new ObjectParameter("Compagnie", compagnie) :
                new ObjectParameter("Compagnie", typeof(string));
    
            var startingPathParameter = startingPath != null ?
                new ObjectParameter("StartingPath", startingPath) :
                new ObjectParameter("StartingPath", typeof(string));
    
            var impersonateUserParameter = impersonateUser != null ?
                new ObjectParameter("ImpersonateUser", impersonateUser) :
                new ObjectParameter("ImpersonateUser", typeof(string));
    
            var remotePathParameter = remotePath != null ?
                new ObjectParameter("RemotePath", remotePath) :
                new ObjectParameter("RemotePath", typeof(string));
    
            var mapperSeulementParameter = mapperSeulement.HasValue ?
                new ObjectParameter("MapperSeulement", mapperSeulement) :
                new ObjectParameter("MapperSeulement", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AjouterServeur", nomParameter, iPParameter, descriptionParameter, domaineParameter, compagnieParameter, startingPathParameter, impersonateUserParameter, remotePathParameter, mapperSeulementParameter);
        }
    
        public virtual int usp_ArchiverProjet(string projetID)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ArchiverProjet", projetIDParameter);
        }
    
        public virtual int usp_CopierModeleSelection(string nom, string description, Nullable<int> modeleID, string utilisateurId, Nullable<int> iDSource, ObjectParameter dernierSelection)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("Nom", nom) :
                new ObjectParameter("Nom", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var modeleIDParameter = modeleID.HasValue ?
                new ObjectParameter("ModeleID", modeleID) :
                new ObjectParameter("ModeleID", typeof(int));
    
            var utilisateurIdParameter = utilisateurId != null ?
                new ObjectParameter("UtilisateurId", utilisateurId) :
                new ObjectParameter("UtilisateurId", typeof(string));
    
            var iDSourceParameter = iDSource.HasValue ?
                new ObjectParameter("IDSource", iDSource) :
                new ObjectParameter("IDSource", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CopierModeleSelection", nomParameter, descriptionParameter, modeleIDParameter, utilisateurIdParameter, iDSourceParameter, dernierSelection);
        }
    
        public virtual int usp_Create_TTSecurity_BatchFile(string sServeur, string projet, Nullable<int> idOfQuery, string pathBatchFile, ObjectParameter myBatchFile)
        {
            var sServeurParameter = sServeur != null ?
                new ObjectParameter("sServeur", sServeur) :
                new ObjectParameter("sServeur", typeof(string));
    
            var projetParameter = projet != null ?
                new ObjectParameter("Projet", projet) :
                new ObjectParameter("Projet", typeof(string));
    
            var idOfQueryParameter = idOfQuery.HasValue ?
                new ObjectParameter("idOfQuery", idOfQuery) :
                new ObjectParameter("idOfQuery", typeof(int));
    
            var pathBatchFileParameter = pathBatchFile != null ?
                new ObjectParameter("pathBatchFile", pathBatchFile) :
                new ObjectParameter("pathBatchFile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Create_TTSecurity_BatchFile", sServeurParameter, projetParameter, idOfQueryParameter, pathBatchFileParameter, myBatchFile);
        }
    
        public virtual ObjectResult<string> usp_IsProjectExist(string projetId)
        {
            var projetIdParameter = projetId != null ?
                new ObjectParameter("ProjetId", projetId) :
                new ObjectParameter("ProjetId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_IsProjectExist", projetIdParameter);
        }
    
        public virtual ObjectResult<string> usp_IsProjectExistBPRProject(string projetId)
        {
            var projetIdParameter = projetId != null ?
                new ObjectParameter("ProjetId", projetId) :
                new ObjectParameter("ProjetId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_IsProjectExistBPRProject", projetIdParameter);
        }
    
        public virtual int usp_MAJ_SecuriteTTProjet(string projctid, Nullable<byte> doDelBatFile)
        {
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            var doDelBatFileParameter = doDelBatFile.HasValue ?
                new ObjectParameter("DoDelBatFile", doDelBatFile) :
                new ObjectParameter("DoDelBatFile", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MAJ_SecuriteTTProjet", projctidParameter, doDelBatFileParameter);
        }
    
        public virtual int usp_MAJ_SecuriteTTProjet_BK_viewCode(string serveur, string projctid, ObjectParameter fileOutput)
        {
            var serveurParameter = serveur != null ?
                new ObjectParameter("serveur", serveur) :
                new ObjectParameter("serveur", typeof(string));
    
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MAJ_SecuriteTTProjet_BK_viewCode", serveurParameter, projctidParameter, fileOutput);
        }
    
        public virtual int usp_MAJ_SecuriteTTProjet_test(string serveur, string projctid, ObjectParameter fileOutput)
        {
            var serveurParameter = serveur != null ?
                new ObjectParameter("serveur", serveur) :
                new ObjectParameter("serveur", typeof(string));
    
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MAJ_SecuriteTTProjet_test", serveurParameter, projctidParameter, fileOutput);
        }
    
        public virtual int usp_MAJ_SecuriteTTProjet_TT_Dev(string serveur, string projctid, ObjectParameter fileOutput)
        {
            var serveurParameter = serveur != null ?
                new ObjectParameter("serveur", serveur) :
                new ObjectParameter("serveur", typeof(string));
    
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MAJ_SecuriteTTProjet_TT_Dev", serveurParameter, projctidParameter, fileOutput);
        }
    
        public virtual int usp_MAJ_SecuriteTTProjetSI1(string serveur, string projctid)
        {
            var serveurParameter = serveur != null ?
                new ObjectParameter("serveur", serveur) :
                new ObjectParameter("serveur", typeof(string));
    
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MAJ_SecuriteTTProjetSI1", serveurParameter, projctidParameter);
        }
    
        public virtual int usp_ModifierProjet(string projetID, Nullable<int> modeleSecuriteId, Nullable<int> serveurID, Nullable<int> typeProjet, string parent, string utilisateurId, Nullable<int> etatProjetId)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            var modeleSecuriteIdParameter = modeleSecuriteId.HasValue ?
                new ObjectParameter("ModeleSecuriteId", modeleSecuriteId) :
                new ObjectParameter("ModeleSecuriteId", typeof(int));
    
            var serveurIDParameter = serveurID.HasValue ?
                new ObjectParameter("ServeurID", serveurID) :
                new ObjectParameter("ServeurID", typeof(int));
    
            var typeProjetParameter = typeProjet.HasValue ?
                new ObjectParameter("TypeProjet", typeProjet) :
                new ObjectParameter("TypeProjet", typeof(int));
    
            var parentParameter = parent != null ?
                new ObjectParameter("Parent", parent) :
                new ObjectParameter("Parent", typeof(string));
    
            var utilisateurIdParameter = utilisateurId != null ?
                new ObjectParameter("UtilisateurId", utilisateurId) :
                new ObjectParameter("UtilisateurId", typeof(string));
    
            var etatProjetIdParameter = etatProjetId.HasValue ?
                new ObjectParameter("EtatProjetId", etatProjetId) :
                new ObjectParameter("EtatProjetId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ModifierProjet", projetIDParameter, modeleSecuriteIdParameter, serveurIDParameter, typeProjetParameter, parentParameter, utilisateurIdParameter, etatProjetIdParameter);
        }
    
        public virtual int usp_ModifierServeur(string nom, string iP, string description, string domaine, string compagnie, string startingPath, string impersonateUser, string remotePath, Nullable<int> mapperSeulement, Nullable<int> iD)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("Nom", nom) :
                new ObjectParameter("Nom", typeof(string));
    
            var iPParameter = iP != null ?
                new ObjectParameter("IP", iP) :
                new ObjectParameter("IP", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var domaineParameter = domaine != null ?
                new ObjectParameter("Domaine", domaine) :
                new ObjectParameter("Domaine", typeof(string));
    
            var compagnieParameter = compagnie != null ?
                new ObjectParameter("Compagnie", compagnie) :
                new ObjectParameter("Compagnie", typeof(string));
    
            var startingPathParameter = startingPath != null ?
                new ObjectParameter("StartingPath", startingPath) :
                new ObjectParameter("StartingPath", typeof(string));
    
            var impersonateUserParameter = impersonateUser != null ?
                new ObjectParameter("ImpersonateUser", impersonateUser) :
                new ObjectParameter("ImpersonateUser", typeof(string));
    
            var remotePathParameter = remotePath != null ?
                new ObjectParameter("RemotePath", remotePath) :
                new ObjectParameter("RemotePath", typeof(string));
    
            var mapperSeulementParameter = mapperSeulement.HasValue ?
                new ObjectParameter("MapperSeulement", mapperSeulement) :
                new ObjectParameter("MapperSeulement", typeof(int));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ModifierServeur", nomParameter, iPParameter, descriptionParameter, domaineParameter, compagnieParameter, startingPathParameter, impersonateUserParameter, remotePathParameter, mapperSeulementParameter, iDParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirCompagnie_Result> usp_ObtenirCompagnie(Nullable<int> compagnieId)
        {
            var compagnieIdParameter = compagnieId.HasValue ?
                new ObjectParameter("CompagnieId", compagnieId) :
                new ObjectParameter("CompagnieId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirCompagnie_Result>("usp_ObtenirCompagnie", compagnieIdParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirEtatProjet_Result> usp_ObtenirEtatProjet(Nullable<int> etatProjet)
        {
            var etatProjetParameter = etatProjet.HasValue ?
                new ObjectParameter("EtatProjet", etatProjet) :
                new ObjectParameter("EtatProjet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirEtatProjet_Result>("usp_ObtenirEtatProjet", etatProjetParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirModele_Result> usp_ObtenirModele(Nullable<int> modeleID)
        {
            var modeleIDParameter = modeleID.HasValue ?
                new ObjectParameter("ModeleID", modeleID) :
                new ObjectParameter("ModeleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirModele_Result>("usp_ObtenirModele", modeleIDParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirModeleParProjet_Result> usp_ObtenirModeleParProjet(string projetID)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirModeleParProjet_Result>("usp_ObtenirModeleParProjet", projetIDParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirModeleSecurite_Result> usp_ObtenirModeleSecurite(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirModeleSecurite_Result>("usp_ObtenirModeleSecurite", iDParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirModeleSelection_Result> usp_ObtenirModeleSelection(Nullable<int> modeleSelectionId)
        {
            var modeleSelectionIdParameter = modeleSelectionId.HasValue ?
                new ObjectParameter("ModeleSelectionId", modeleSelectionId) :
                new ObjectParameter("ModeleSelectionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirModeleSelection_Result>("usp_ObtenirModeleSelection", modeleSelectionIdParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirProjet_Result> usp_ObtenirProjet(string projet)
        {
            var projetParameter = projet != null ?
                new ObjectParameter("Projet", projet) :
                new ObjectParameter("Projet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirProjet_Result>("usp_ObtenirProjet", projetParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirProjet_Securite_Result> usp_ObtenirProjet_Securite(string projet)
        {
            var projetParameter = projet != null ?
                new ObjectParameter("Projet", projet) :
                new ObjectParameter("Projet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirProjet_Securite_Result>("usp_ObtenirProjet_Securite", projetParameter);
        }
    
        public virtual ObjectResult<string> usp_ObtenirProjet_TTPlus(Nullable<int> ser_ID)
        {
            var ser_IDParameter = ser_ID.HasValue ?
                new ObjectParameter("ser_ID", ser_ID) :
                new ObjectParameter("ser_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_ObtenirProjet_TTPlus", ser_IDParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirProjetComptable_Result> usp_ObtenirProjetComptable(string projet)
        {
            var projetParameter = projet != null ?
                new ObjectParameter("Projet", projet) :
                new ObjectParameter("Projet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirProjetComptable_Result>("usp_ObtenirProjetComptable", projetParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirProjetGroupe_Result> usp_ObtenirProjetGroupe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirProjetGroupe_Result>("usp_ObtenirProjetGroupe");
        }
    
        public virtual ObjectResult<usp_ObtenirProjetParServeur_Result> usp_ObtenirProjetParServeur(Nullable<int> serverID)
        {
            var serverIDParameter = serverID.HasValue ?
                new ObjectParameter("ServerID", serverID) :
                new ObjectParameter("ServerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirProjetParServeur_Result>("usp_ObtenirProjetParServeur", serverIDParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirProjetProposition_Result> usp_ObtenirProjetProposition()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirProjetProposition_Result>("usp_ObtenirProjetProposition");
        }
    
        public virtual ObjectResult<usp_ObtenirRepertoire_Result> usp_ObtenirRepertoire(Nullable<int> modeleId, Nullable<int> repertoireId)
        {
            var modeleIdParameter = modeleId.HasValue ?
                new ObjectParameter("ModeleId", modeleId) :
                new ObjectParameter("ModeleId", typeof(int));
    
            var repertoireIdParameter = repertoireId.HasValue ?
                new ObjectParameter("RepertoireId", repertoireId) :
                new ObjectParameter("RepertoireId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirRepertoire_Result>("usp_ObtenirRepertoire", modeleIdParameter, repertoireIdParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirRepertoireParModele_Result> usp_ObtenirRepertoireParModele(Nullable<int> modeleId)
        {
            var modeleIdParameter = modeleId.HasValue ?
                new ObjectParameter("ModeleId", modeleId) :
                new ObjectParameter("ModeleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirRepertoireParModele_Result>("usp_ObtenirRepertoireParModele", modeleIdParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirRepertoireParModeleBaseSeulement_Result> usp_ObtenirRepertoireParModeleBaseSeulement(Nullable<int> modeleId)
        {
            var modeleIdParameter = modeleId.HasValue ?
                new ObjectParameter("ModeleId", modeleId) :
                new ObjectParameter("ModeleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirRepertoireParModeleBaseSeulement_Result>("usp_ObtenirRepertoireParModeleBaseSeulement", modeleIdParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirRepertoireParModeleSelection_Result> usp_ObtenirRepertoireParModeleSelection(Nullable<int> modeleSelectionId)
        {
            var modeleSelectionIdParameter = modeleSelectionId.HasValue ?
                new ObjectParameter("ModeleSelectionId", modeleSelectionId) :
                new ObjectParameter("ModeleSelectionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirRepertoireParModeleSelection_Result>("usp_ObtenirRepertoireParModeleSelection", modeleSelectionIdParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirRepertoireParProjet_Result> usp_ObtenirRepertoireParProjet(string projetId, Nullable<int> modeleId)
        {
            var projetIdParameter = projetId != null ?
                new ObjectParameter("ProjetId", projetId) :
                new ObjectParameter("ProjetId", typeof(string));
    
            var modeleIdParameter = modeleId.HasValue ?
                new ObjectParameter("ModeleId", modeleId) :
                new ObjectParameter("ModeleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirRepertoireParProjet_Result>("usp_ObtenirRepertoireParProjet", projetIdParameter, modeleIdParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirRepertoireParProjetTTProjetPlus_LG_Result> usp_ObtenirRepertoireParProjetTTProjetPlus_LG(string projetID)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirRepertoireParProjetTTProjetPlus_LG_Result>("usp_ObtenirRepertoireParProjetTTProjetPlus_LG", projetIDParameter);
        }
    
        public virtual int usp_obtenirSecuriteTT(string projctid)
        {
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_obtenirSecuriteTT", projctidParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirServeur_Result> usp_ObtenirServeur(Nullable<int> serveurId)
        {
            var serveurIdParameter = serveurId.HasValue ?
                new ObjectParameter("ServeurId", serveurId) :
                new ObjectParameter("ServeurId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirServeur_Result>("usp_ObtenirServeur", serveurIdParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirServeurParProjet_Result> usp_ObtenirServeurParProjet(string projetId)
        {
            var projetIdParameter = projetId != null ?
                new ObjectParameter("ProjetId", projetId) :
                new ObjectParameter("ProjetId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirServeurParProjet_Result>("usp_ObtenirServeurParProjet", projetIdParameter);
        }
    
        public virtual ObjectResult<usp_ProjetparPage_Result> usp_ProjetparPage(Nullable<int> projet)
        {
            var projetParameter = projet.HasValue ?
                new ObjectParameter("projet", projet) :
                new ObjectParameter("projet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ProjetparPage_Result>("usp_ProjetparPage", projetParameter);
        }
    
        public virtual int usp_ProjetSecuriseTT(string projctid)
        {
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ProjetSecuriseTT", projctidParameter);
        }
    
        public virtual int usp_RapportCorrespondance(string sER_Nom, string pRO_Id, string pathType, string scanType, Nullable<bool> fullPathExist)
        {
            var sER_NomParameter = sER_Nom != null ?
                new ObjectParameter("SER_Nom", sER_Nom) :
                new ObjectParameter("SER_Nom", typeof(string));
    
            var pRO_IdParameter = pRO_Id != null ?
                new ObjectParameter("PRO_Id", pRO_Id) :
                new ObjectParameter("PRO_Id", typeof(string));
    
            var pathTypeParameter = pathType != null ?
                new ObjectParameter("PathType", pathType) :
                new ObjectParameter("PathType", typeof(string));
    
            var scanTypeParameter = scanType != null ?
                new ObjectParameter("ScanType", scanType) :
                new ObjectParameter("ScanType", typeof(string));
    
            var fullPathExistParameter = fullPathExist.HasValue ?
                new ObjectParameter("FullPathExist", fullPathExist) :
                new ObjectParameter("FullPathExist", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RapportCorrespondance", sER_NomParameter, pRO_IdParameter, pathTypeParameter, scanTypeParameter, fullPathExistParameter);
        }
    
        public virtual ObjectResult<usp_RechercherModeleSecurite_Result> usp_RechercherModeleSecurite(Nullable<int> mOD_Id)
        {
            var mOD_IdParameter = mOD_Id.HasValue ?
                new ObjectParameter("MOD_Id", mOD_Id) :
                new ObjectParameter("MOD_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RechercherModeleSecurite_Result>("usp_RechercherModeleSecurite", mOD_IdParameter);
        }
    
        public virtual ObjectResult<usp_RechercherModeleSelection_Result> usp_RechercherModeleSelection(string utilisateurId, Nullable<int> modeleId)
        {
            var utilisateurIdParameter = utilisateurId != null ?
                new ObjectParameter("UtilisateurId", utilisateurId) :
                new ObjectParameter("UtilisateurId", typeof(string));
    
            var modeleIdParameter = modeleId.HasValue ?
                new ObjectParameter("ModeleId", modeleId) :
                new ObjectParameter("ModeleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RechercherModeleSelection_Result>("usp_RechercherModeleSelection", utilisateurIdParameter, modeleIdParameter);
        }
    
        public virtual ObjectResult<usp_RechercherProjetComptable_Result> usp_RechercherProjetComptable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RechercherProjetComptable_Result>("usp_RechercherProjetComptable");
        }
    
        public virtual ObjectResult<usp_RechercherRepertoire_Result> usp_RechercherRepertoire(Nullable<int> modeleId)
        {
            var modeleIdParameter = modeleId.HasValue ?
                new ObjectParameter("ModeleId", modeleId) :
                new ObjectParameter("ModeleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RechercherRepertoire_Result>("usp_RechercherRepertoire", modeleIdParameter);
        }
    
        public virtual ObjectResult<usp_RechercherRepertoireParREP_Code_Detail_Result> usp_RechercherRepertoireParREP_Code_Detail(Nullable<int> modeleId, string rEP_Code)
        {
            var modeleIdParameter = modeleId.HasValue ?
                new ObjectParameter("ModeleId", modeleId) :
                new ObjectParameter("ModeleId", typeof(int));
    
            var rEP_CodeParameter = rEP_Code != null ?
                new ObjectParameter("REP_Code", rEP_Code) :
                new ObjectParameter("REP_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RechercherRepertoireParREP_Code_Detail_Result>("usp_RechercherRepertoireParREP_Code_Detail", modeleIdParameter, rEP_CodeParameter);
        }
    
        public virtual ObjectResult<string> usp_RechercherRepertoireParREP_Code_Sommaire(Nullable<int> modeleId)
        {
            var modeleIdParameter = modeleId.HasValue ?
                new ObjectParameter("ModeleId", modeleId) :
                new ObjectParameter("ModeleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_RechercherRepertoireParREP_Code_Sommaire", modeleIdParameter);
        }
    
        public virtual int usp_SupprimerModeleSelection(Nullable<int> modeleSelectionId)
        {
            var modeleSelectionIdParameter = modeleSelectionId.HasValue ?
                new ObjectParameter("ModeleSelectionId", modeleSelectionId) :
                new ObjectParameter("ModeleSelectionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SupprimerModeleSelection", modeleSelectionIdParameter);
        }
    
        public virtual int usp_SupprimerModeleSelectionRepertoire(Nullable<int> modeleSelectionID)
        {
            var modeleSelectionIDParameter = modeleSelectionID.HasValue ?
                new ObjectParameter("ModeleSelectionID", modeleSelectionID) :
                new ObjectParameter("ModeleSelectionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SupprimerModeleSelectionRepertoire", modeleSelectionIDParameter);
        }
    
        public virtual int usp_SupprimerServeur(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SupprimerServeur", iDParameter);
        }
    
        public virtual int usp_TransfererProjet(string projetId)
        {
            var projetIdParameter = projetId != null ?
                new ObjectParameter("ProjetId", projetId) :
                new ObjectParameter("ProjetId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_TransfererProjet", projetIdParameter);
        }
    
        public virtual ObjectResult<usp_GetChildrenByParentIDandModID_Result> usp_GetChildrenByParentIDandModID(Nullable<int> mOD_Id, Nullable<int> rep_id)
        {
            var mOD_IdParameter = mOD_Id.HasValue ?
                new ObjectParameter("MOD_Id", mOD_Id) :
                new ObjectParameter("MOD_Id", typeof(int));
    
            var rep_idParameter = rep_id.HasValue ?
                new ObjectParameter("rep_id", rep_id) :
                new ObjectParameter("rep_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetChildrenByParentIDandModID_Result>("usp_GetChildrenByParentIDandModID", mOD_IdParameter, rep_idParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirRepertoireParProjetTTProjetPlus_Result> usp_ObtenirRepertoireParProjetTTProjetPlus(string projetID)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirRepertoireParProjetTTProjetPlus_Result>("usp_ObtenirRepertoireParProjetTTProjetPlus", projetIDParameter);
        }
    
        public virtual ObjectResult<string> usp_TT_Security_Archive_TTProjetPlus(string projctid, Nullable<byte> projctHas10Confidentiel, Nullable<byte> doDelBatFile)
        {
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            var projctHas10ConfidentielParameter = projctHas10Confidentiel.HasValue ?
                new ObjectParameter("projctHas10Confidentiel", projctHas10Confidentiel) :
                new ObjectParameter("projctHas10Confidentiel", typeof(byte));
    
            var doDelBatFileParameter = doDelBatFile.HasValue ?
                new ObjectParameter("DoDelBatFile", doDelBatFile) :
                new ObjectParameter("DoDelBatFile", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_TT_Security_Archive_TTProjetPlus", projctidParameter, projctHas10ConfidentielParameter, doDelBatFileParameter);
        }
    
        public virtual ObjectResult<string> usp_NEW_TT_Security_INPROGRESS_TTProjetPlus(string projctid, Nullable<byte> doDelBatFile)
        {
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            var doDelBatFileParameter = doDelBatFile.HasValue ?
                new ObjectParameter("DoDelBatFile", doDelBatFile) :
                new ObjectParameter("DoDelBatFile", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_NEW_TT_Security_INPROGRESS_TTProjetPlus", projctidParameter, doDelBatFileParameter);
        }
    
        public virtual ObjectResult<string> usp_isProject_TTPlus(string projctid)
        {
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_isProject_TTPlus", projctidParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirRepertoireParProjetEtModSelectionTTProjetPlus_Result> usp_ObtenirRepertoireParProjetEtModSelectionTTProjetPlus(string projetID, Nullable<int> modeleSelectionId)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            var modeleSelectionIdParameter = modeleSelectionId.HasValue ?
                new ObjectParameter("ModeleSelectionId", modeleSelectionId) :
                new ObjectParameter("ModeleSelectionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirRepertoireParProjetEtModSelectionTTProjetPlus_Result>("usp_ObtenirRepertoireParProjetEtModSelectionTTProjetPlus", projetIDParameter, modeleSelectionIdParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirArborescenceRepertoireModeleTTProjetPlus_Result> usp_ObtenirArborescenceRepertoireModeleTTProjetPlus(string modidParameter)
        {
            var modidParameterParameter = modidParameter != null ?
                new ObjectParameter("modidParameter", modidParameter) :
                new ObjectParameter("modidParameter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirArborescenceRepertoireModeleTTProjetPlus_Result>("usp_ObtenirArborescenceRepertoireModeleTTProjetPlus", modidParameterParameter);
        }
    
        public virtual int usp_AjouterRepertoireProjet_TTProjetPlus(string projetID, Nullable<int> modSelId)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            var modSelIdParameter = modSelId.HasValue ?
                new ObjectParameter("ModSelId", modSelId) :
                new ObjectParameter("ModSelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AjouterRepertoireProjet_TTProjetPlus", projetIDParameter, modSelIdParameter);
        }
    
        public virtual ObjectResult<usp_GetSecurityDirectoryForProject_Result> usp_GetSecurityDirectoryForProject(Nullable<int> rep_id, string pro_id)
        {
            var rep_idParameter = rep_id.HasValue ?
                new ObjectParameter("rep_id", rep_id) :
                new ObjectParameter("rep_id", typeof(int));
    
            var pro_idParameter = pro_id != null ?
                new ObjectParameter("pro_id", pro_id) :
                new ObjectParameter("pro_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSecurityDirectoryForProject_Result>("usp_GetSecurityDirectoryForProject", rep_idParameter, pro_idParameter);
        }
    
        public virtual ObjectResult<usp_GetSecurityDirectoryProjectList_Result> usp_GetSecurityDirectoryProjectList(string tTAccount)
        {
            var tTAccountParameter = tTAccount != null ?
                new ObjectParameter("TTAccount", tTAccount) :
                new ObjectParameter("TTAccount", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSecurityDirectoryProjectList_Result>("usp_GetSecurityDirectoryProjectList", tTAccountParameter);
        }
    
        public virtual int usp_Add_SecurityDirectoryRightsList(string projctid, Nullable<int> repId, string tAccounts)
        {
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            var repIdParameter = repId.HasValue ?
                new ObjectParameter("repId", repId) :
                new ObjectParameter("repId", typeof(int));
    
            var tAccountsParameter = tAccounts != null ?
                new ObjectParameter("tAccounts", tAccounts) :
                new ObjectParameter("tAccounts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Add_SecurityDirectoryRightsList", projctidParameter, repIdParameter, tAccountsParameter);
        }
    
        public virtual int usp_Delete_SecurityDirectoryRightsList(string projctid, Nullable<int> repId, string tAccounts)
        {
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            var repIdParameter = repId.HasValue ?
                new ObjectParameter("repId", repId) :
                new ObjectParameter("repId", typeof(int));
    
            var tAccountsParameter = tAccounts != null ?
                new ObjectParameter("tAccounts", tAccounts) :
                new ObjectParameter("tAccounts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Delete_SecurityDirectoryRightsList", projctidParameter, repIdParameter, tAccountsParameter);
        }
    
        public virtual ObjectResult<usp_GetSecurityDirectoryFoldersList_Result> usp_GetSecurityDirectoryFoldersList(string tTAccount, string pro_id)
        {
            var tTAccountParameter = tTAccount != null ?
                new ObjectParameter("TTAccount", tTAccount) :
                new ObjectParameter("TTAccount", typeof(string));
    
            var pro_idParameter = pro_id != null ?
                new ObjectParameter("pro_id", pro_id) :
                new ObjectParameter("pro_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSecurityDirectoryFoldersList_Result>("usp_GetSecurityDirectoryFoldersList", tTAccountParameter, pro_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_isProjectSecurityNeedsUpdate(string pRO_ID)
        {
            var pRO_IDParameter = pRO_ID != null ?
                new ObjectParameter("PRO_ID", pRO_ID) :
                new ObjectParameter("PRO_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_isProjectSecurityNeedsUpdate", pRO_IDParameter);
        }
    
        public virtual ObjectResult<usp_GetSecurityDirectoryADGroupForAdmin_Result> usp_GetSecurityDirectoryADGroupForAdmin(string tTAccount)
        {
            var tTAccountParameter = tTAccount != null ?
                new ObjectParameter("TTAccount", tTAccount) :
                new ObjectParameter("TTAccount", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSecurityDirectoryADGroupForAdmin_Result>("usp_GetSecurityDirectoryADGroupForAdmin", tTAccountParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirProjetEtServeurCorrespondant_Result> usp_ObtenirProjetEtServeurCorrespondant()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirProjetEtServeurCorrespondant_Result>("usp_ObtenirProjetEtServeurCorrespondant");
        }
    
        public virtual int usp_Nasuni_NewObtenirRepertoireParProjetTTProjetPlus(string projetID, string modId, Nullable<bool> report)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            var modIdParameter = modId != null ?
                new ObjectParameter("modId", modId) :
                new ObjectParameter("modId", typeof(string));
    
            var reportParameter = report.HasValue ?
                new ObjectParameter("Report", report) :
                new ObjectParameter("Report", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Nasuni_NewObtenirRepertoireParProjetTTProjetPlus", projetIDParameter, modIdParameter, reportParameter);
        }
    
        public virtual int usp_ObtenirRepertoireParProjetTTProjetPlusNasuni(string projetID, string modId)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            var modIdParameter = modId != null ?
                new ObjectParameter("modId", modId) :
                new ObjectParameter("modId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ObtenirRepertoireParProjetTTProjetPlusNasuni", projetIDParameter, modIdParameter);
        }
    
        public virtual int usp_Nasuni_SecuriserServeurouProjet10Conf(string serveur, string projet, Nullable<byte> rafraichirDonnees)
        {
            var serveurParameter = serveur != null ?
                new ObjectParameter("Serveur", serveur) :
                new ObjectParameter("Serveur", typeof(string));
    
            var projetParameter = projet != null ?
                new ObjectParameter("Projet", projet) :
                new ObjectParameter("Projet", typeof(string));
    
            var rafraichirDonneesParameter = rafraichirDonnees.HasValue ?
                new ObjectParameter("rafraichirDonnees", rafraichirDonnees) :
                new ObjectParameter("rafraichirDonnees", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Nasuni_SecuriserServeurouProjet10Conf", serveurParameter, projetParameter, rafraichirDonneesParameter);
        }
    
        public virtual int usp_Nasuni_Projet10Conf_Table(string serveur, string projet, Nullable<byte> rafraichirDonnees)
        {
            var serveurParameter = serveur != null ?
                new ObjectParameter("Serveur", serveur) :
                new ObjectParameter("Serveur", typeof(string));
    
            var projetParameter = projet != null ?
                new ObjectParameter("Projet", projet) :
                new ObjectParameter("Projet", typeof(string));
    
            var rafraichirDonneesParameter = rafraichirDonnees.HasValue ?
                new ObjectParameter("rafraichirDonnees", rafraichirDonnees) :
                new ObjectParameter("rafraichirDonnees", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Nasuni_Projet10Conf_Table", serveurParameter, projetParameter, rafraichirDonneesParameter);
        }
    
        public virtual int usp_Delete_tbl_ObtenirRepertoireParProjetTTProjetPlusNasuni(Nullable<int> seqID)
        {
            var seqIDParameter = seqID.HasValue ?
                new ObjectParameter("seqID", seqID) :
                new ObjectParameter("seqID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Delete_tbl_ObtenirRepertoireParProjetTTProjetPlusNasuni", seqIDParameter);
        }
    
        public virtual int usp_AddEmp60Conf(string tTAccount, string projctid)
        {
            var tTAccountParameter = tTAccount != null ?
                new ObjectParameter("TTAccount", tTAccount) :
                new ObjectParameter("TTAccount", typeof(string));
    
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AddEmp60Conf", tTAccountParameter, projctidParameter);
        }
    
        public virtual ObjectResult<usp_AddSecurityUser60Conf_Result> usp_AddSecurityUser60Conf(string projctid)
        {
            var projctidParameter = projctid != null ?
                new ObjectParameter("projctid", projctid) :
                new ObjectParameter("projctid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AddSecurityUser60Conf_Result>("usp_AddSecurityUser60Conf", projctidParameter);
        }
    
        public virtual ObjectResult<usp_ObtenirRepertoireParProjetTTProjetPlus_LG1_Result> usp_ObtenirRepertoireParProjetTTProjetPlus_LG1(string projetID)
        {
            var projetIDParameter = projetID != null ?
                new ObjectParameter("ProjetID", projetID) :
                new ObjectParameter("ProjetID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenirRepertoireParProjetTTProjetPlus_LG1_Result>("usp_ObtenirRepertoireParProjetTTProjetPlus_LG1", projetIDParameter);
        }
    
        public virtual int usp_ModifierStatutProjectASecuriser(string projet)
        {
            var projetParameter = projet != null ?
                new ObjectParameter("Projet", projet) :
                new ObjectParameter("Projet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ModifierStatutProjectASecuriser", projetParameter);
        }
    
        public virtual ObjectResult<usp_ListeProjetaSecuriser_Result> usp_ListeProjetaSecuriser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListeProjetaSecuriser_Result>("usp_ListeProjetaSecuriser");
        }
    
        public virtual int usp_ArchiveProjet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ArchiveProjet");
        }
    }
}
