//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__SMprojet
    {
        public string company { get; set; }
        public int company_id { get; set; }
        public int project_id { get; set; }
        public string gl_period { get; set; }
        public string project_number { get; set; }
        public string project_status_code { get; set; }
        public string project_mgr_name { get; set; }
        public string project_mgr_num { get; set; }
        public string program_mgr_name { get; set; }
        public string program_mgr_num { get; set; }
        public string bill_specialist_name { get; set; }
        public string project_currency_code { get; set; }
        public string distribution_rule { get; set; }
        public string contract_type { get; set; }
        public string acct_group { get; set; }
        public Nullable<int> acct_group_id { get; set; }
        public string acct_center { get; set; }
        public Nullable<int> acct_center_id { get; set; }
        public System.DateTime project_start_date { get; set; }
        public System.DateTime project_end_date { get; set; }
        public decimal cost_budget { get; set; }
        public decimal revenue_budget { get; set; }
        public Nullable<decimal> hrs_budget { get; set; }
        public decimal cost_ptd { get; set; }
        public decimal revenue_ptd { get; set; }
        public decimal profit_ptd { get; set; }
        public double profit_pct_ptd { get; set; }
        public decimal hrs_ptd { get; set; }
        public decimal cost_qtd { get; set; }
        public decimal revenue_qtd { get; set; }
        public decimal profit_qtd { get; set; }
        public double profit_pct_qtd { get; set; }
        public decimal hrs_qtd { get; set; }
        public decimal cost_ytd { get; set; }
        public decimal revenue_ytd { get; set; }
        public decimal profit_ytd { get; set; }
        public double profit_pct_ytd { get; set; }
        public decimal hrs_ytd { get; set; }
        public decimal cost_itd { get; set; }
        public decimal revenue_itd { get; set; }
        public decimal profit_itd { get; set; }
        public double profit_pct_itd { get; set; }
        public decimal hrs_itd { get; set; }
        public decimal lbr_cost_itd { get; set; }
        public decimal sub_cost_itd { get; set; }
        public decimal odc_cost_itd { get; set; }
        public double cost_pct_complete { get; set; }
        public string customer_name { get; set; }
        public string customer_number { get; set; }
        public string end_client_name { get; set; }
        public string sf330 { get; set; }
        public string programs { get; set; }
        public string po_number { get; set; }
        public string project_desc { get; set; }
        public decimal total_billed { get; set; }
        public decimal total_invoiced { get; set; }
        public double inv_pct_complete { get; set; }
        public decimal total_unbilled { get; set; }
        public decimal unbilled_0_30 { get; set; }
        public decimal unbilled_31_60 { get; set; }
        public decimal unbilled_61_90 { get; set; }
        public decimal unbilled_91_120 { get; set; }
        public decimal unbilled_120 { get; set; }
        public decimal total_unearned { get; set; }
        public decimal wip_itd { get; set; }
        public decimal nonbill_itd { get; set; }
        public decimal total_ar { get; set; }
        public decimal ar_0_30 { get; set; }
        public decimal ar_31_60 { get; set; }
        public decimal ar_61_90 { get; set; }
        public decimal ar_91_120 { get; set; }
        public decimal ar_120 { get; set; }
        public decimal total_billable { get; set; }
        public decimal lbr_billable { get; set; }
        public decimal sub_billable { get; set; }
        public decimal odc_billable { get; set; }
        public decimal event_billable { get; set; }
        public decimal nonbill_hrs_itd { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime Period_Week_Date { get; set; }
        public System.DateTime pa_period_end_date { get; set; }
        public string PROJECT_NAME { get; set; }
        public Nullable<decimal> JV_AMT_PTD { get; set; }
        public Nullable<decimal> JV_AMT_QTD { get; set; }
        public Nullable<decimal> JV_AMT_YTD { get; set; }
        public Nullable<decimal> JV_AMT_ITD { get; set; }
        public string projctid { get; set; }
    }
}
