//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline_Logs
    {
        public int Discipline_Logs_ID { get; set; }
        public string SubmitBy { get; set; }
        public string Action { get; set; }
        public string ForEmployeeTTAccount { get; set; }
        public Nullable<int> Disc_ID { get; set; }
        public Nullable<int> DocProj_ID { get; set; }
        public Nullable<System.DateTime> UTCDateTime { get; set; }
    }
}
