//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocProj_ADGroup
    {
        public int DocProj_ADGroup_ID { get; set; }
        public int DocProj_ID { get; set; }
        public string ADGroup_Write { get; set; }
        public string ADGroup_Read { get; set; }
        public int isActive { get; set; }
        public string AvailableToEmployeesMembersOf { get; set; }
    }
}
