//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class droit
    {
        public decimal id_droit { get; set; }
        public decimal id_utilisateur { get; set; }
        public string admin { get; set; }
        public Nullable<decimal> id_pole { get; set; }
        public Nullable<decimal> id_activite { get; set; }
        public Nullable<decimal> id_agence { get; set; }
    }
}
