//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DROPDOWN_LIST
    {
        public int ID { get; set; }
        public string List_ID { get; set; }
        public string Item_Name { get; set; }
        public bool isActive { get; set; }
    }
}
