//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_GRIDSTATE
    {
        public string Employee_Number { get; set; }
        public string Grid_Id { get; set; }
        public string Grid_State { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
    }
}
