//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fiche_esp_old
    {
        public decimal id_fiche { get; set; }
        public Nullable<decimal> id_createur { get; set; }
        public string code_affaire { get; set; }
        public Nullable<decimal> id_activite { get; set; }
        public string localisation { get; set; }
        public string id_province { get; set; }
        public string autre_lieu { get; set; }
        public string id_pays { get; set; }
        public string intitule { get; set; }
        public string intitule_court { get; set; }
        public string description { get; set; }
        public string id_type_mission { get; set; }
        public string mission { get; set; }
        public string particularite { get; set; }
        public string mois_debut { get; set; }
        public string annee_debut { get; set; }
        public string mois_fin { get; set; }
        public string annee_fin { get; set; }
        public Nullable<byte> duree { get; set; }
        public Nullable<decimal> id_type_unite_1 { get; set; }
        public Nullable<float> unite_1 { get; set; }
        public Nullable<decimal> id_type_unite_2 { get; set; }
        public Nullable<float> unite_2 { get; set; }
        public Nullable<float> montant_operation { get; set; }
        public Nullable<float> montant_equipe { get; set; }
        public Nullable<float> montant_societe { get; set; }
        public string type_client { get; set; }
        public string client_nom { get; set; }
        public string client_adresse { get; set; }
        public string client_telephone { get; set; }
        public string client_mail { get; set; }
        public string contact_nom { get; set; }
        public string num_ref { get; set; }
        public string architecte { get; set; }
        public string conducteur_operation { get; set; }
        public string equipe { get; set; }
        public string equipe_interne { get; set; }
        public Nullable<decimal> id_agence { get; set; }
        public string id_charge_affaire { get; set; }
        public string proprio { get; set; }
        public string argumentaire_com { get; set; }
        public string code_qualification_opqibi { get; set; }
        public string lastmod_user { get; set; }
        public Nullable<System.DateTime> lastmod_time { get; set; }
        public string lastmod_opqibi { get; set; }
        public string award { get; set; }
        public string nom_award { get; set; }
        public string lastmod_award { get; set; }
        public string imgForFiche { get; set; }
        public string etat { get; set; }
        public string active { get; set; }
        public Nullable<System.DateTime> created_time { get; set; }
        public string ancien_ref { get; set; }
        public string filiale { get; set; }
        public Nullable<int> conception_prevue_mois_debut { get; set; }
        public Nullable<int> conception_prevue_annee_debut { get; set; }
        public Nullable<int> conception_prevue_mois_fin { get; set; }
        public Nullable<int> conception_prevue_annee_fin { get; set; }
        public Nullable<int> conception_finale_mois_debut { get; set; }
        public Nullable<int> conception_finale_annee_debut { get; set; }
        public Nullable<int> conception_finale_mois_fin { get; set; }
        public Nullable<int> conception_finale_annee_fin { get; set; }
        public Nullable<int> plan_prevu_mois_debut { get; set; }
        public Nullable<int> plan_prevu_annee_debut { get; set; }
        public Nullable<int> plan_prevu_mois_fin { get; set; }
        public Nullable<int> plan_prevu_annee_fin { get; set; }
        public Nullable<int> plan_final_mois_debut { get; set; }
        public Nullable<int> plan_final_annee_debut { get; set; }
        public Nullable<int> plan_final_mois_fin { get; set; }
        public Nullable<int> plan_final_annee_fin { get; set; }
        public Nullable<int> construction_prevue_mois_debut { get; set; }
        public Nullable<int> construction_prevue_annee_debut { get; set; }
        public Nullable<int> construction_prevue_mois_fin { get; set; }
        public Nullable<int> construction_prevue_annee_fin { get; set; }
        public Nullable<int> construction_finale_mois_debut { get; set; }
        public Nullable<int> construction_finale_annee_debut { get; set; }
        public Nullable<int> construction_finale_mois_fin { get; set; }
        public Nullable<int> construction_finale_annee_fin { get; set; }
        public string ecart_periode_real { get; set; }
        public Nullable<float> montant_estimation { get; set; }
        public Nullable<float> montant_soumission { get; set; }
        public Nullable<float> montant_final { get; set; }
        public string ecart_cout { get; set; }
        public Nullable<int> changement_bpr { get; set; }
        public Nullable<float> montant_changement_bpr { get; set; }
        public string nature_changement_bpr { get; set; }
        public Nullable<int> changement_client { get; set; }
        public Nullable<float> montant_changement_client { get; set; }
        public string nature_changement_client { get; set; }
        public Nullable<float> structure_prevu { get; set; }
        public Nullable<float> structure_final { get; set; }
        public string ecart_structure { get; set; }
        public Nullable<float> amenagement_prevu { get; set; }
        public Nullable<float> amenagement_final { get; set; }
        public string ecart_amenagement { get; set; }
        public Nullable<float> mecanique_prevu { get; set; }
        public Nullable<float> mecanique_final { get; set; }
        public string ecart_mecanique { get; set; }
        public Nullable<float> electricite_prevu { get; set; }
        public Nullable<float> electricite_final { get; set; }
        public string ecart_electricite { get; set; }
        public Nullable<float> infrastructure_prevu { get; set; }
        public Nullable<float> infrastructure_final { get; set; }
        public string ecart_infrastructure { get; set; }
        public Nullable<float> gestion_prevu { get; set; }
        public Nullable<float> gestion_final { get; set; }
        public string ecart_gestion { get; set; }
        public string autre_nom { get; set; }
        public Nullable<float> autre_prevu { get; set; }
        public Nullable<float> autre_final { get; set; }
        public string ecart_autre { get; set; }
        public Nullable<float> structure_prevu_bpr { get; set; }
        public Nullable<float> structure_final_bpr { get; set; }
        public string ecart_structure_bpr { get; set; }
        public Nullable<float> amenagement_prevu_bpr { get; set; }
        public Nullable<float> amenagement_final_bpr { get; set; }
        public string ecart_amenagement_bpr { get; set; }
        public Nullable<float> mecanique_prevu_bpr { get; set; }
        public Nullable<float> mecanique_final_bpr { get; set; }
        public string ecart_mecanique_bpr { get; set; }
        public Nullable<float> electricite_prevu_bpr { get; set; }
        public Nullable<float> electricite_final_bpr { get; set; }
        public string ecart_electricite_bpr { get; set; }
        public Nullable<float> infrastructure_prevu_bpr { get; set; }
        public Nullable<float> infrastructure_final_bpr { get; set; }
        public string ecart_infrastructure_bpr { get; set; }
        public Nullable<float> gestion_prevu_bpr { get; set; }
        public Nullable<float> gestion_final_bpr { get; set; }
        public string ecart_gestion_bpr { get; set; }
        public string autre_nom_bpr { get; set; }
        public string autre_prevu_bpr { get; set; }
        public string autre_final_bpr { get; set; }
        public string ecart_autre_bpr { get; set; }
        public Nullable<float> eco_energie_prevu { get; set; }
        public Nullable<float> eco_energie_reel { get; set; }
        public Nullable<float> eco_monetaire_prevu { get; set; }
        public Nullable<float> eco_monetaire_reel { get; set; }
        public Nullable<float> pri_prevu { get; set; }
        public Nullable<float> pri_reel { get; set; }
        public Nullable<float> conso_prevu { get; set; }
        public Nullable<float> conso_reel { get; set; }
        public string mesurage_eco { get; set; }
        public string appui_financier_organisme { get; set; }
        public string appui_financier_organisme2 { get; set; }
        public string appui_financier_organisme3 { get; set; }
        public Nullable<float> appui_financier_prevu { get; set; }
        public Nullable<float> appui_financier_prevu2 { get; set; }
        public Nullable<float> appui_financier_prevu3 { get; set; }
        public Nullable<float> appui_financier_reel { get; set; }
        public Nullable<float> appui_financier_reel2 { get; set; }
        public Nullable<float> appui_financier_reel3 { get; set; }
    }
}
