//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListeDocDepotAutomatiqueTQE
    {
        public int Repertoire { get; set; }
        public string SousRepertoire { get; set; }
        public string NumeroDoc { get; set; }
        public string Titre { get; set; }
        public int idItem { get; set; }
    }
}
