//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nasuni_TT_ProjectsToSecured
    {
        public int id { get; set; }
        public Nullable<long> NasuniSeqID { get; set; }
        public string ProjectID { get; set; }
        public System.DateTime DtInserted { get; set; }
        public Nullable<System.DateTime> dtStarted { get; set; }
        public Nullable<System.DateTime> dtFinished { get; set; }
        public Nullable<byte> nbTrial { get; set; }
        public string error { get; set; }
        public Nullable<bool> Completed { get; set; }
    }
}
