//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningProject
    {
        public int OpeningProject_Id { get; set; }
        public Nullable<int> OS_Project_Id { get; set; }
        public Nullable<int> Version_Id { get; set; }
        public Nullable<byte> State { get; set; }
        public string Project_Number { get; set; }
        public string Project_Description { get; set; }
        public string Project_Name { get; set; }
        public Nullable<byte> Billing_Language { get; set; }
        public Nullable<bool> Billing_Format_Paper { get; set; }
        public Nullable<bool> Billing_Format_Electronic { get; set; }
        public string Project_Mgr_Number { get; set; }
        public string Program_Mgr_Number { get; set; }
        public string Bill_Specialist_Number { get; set; }
        public string OtherKM_01 { get; set; }
        public string OtherKM_02 { get; set; }
        public string Initiated_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Last_Modification_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<int> Currency_Id { get; set; }
        public Nullable<System.DateTime> Project_Start_Date { get; set; }
        public Nullable<System.DateTime> Project_End_Date { get; set; }
        public Nullable<int> Distribution_Rule_Id { get; set; }
        public Nullable<int> Contract_Type_Id { get; set; }
        public Nullable<int> Acct_Center_Id { get; set; }
        public Nullable<int> Office_Address_Id { get; set; }
        public Nullable<int> Work_Location_ID { get; set; }
        public Nullable<int> Program_Id { get; set; }
        public Nullable<int> Work_Type_Id { get; set; }
        public Nullable<bool> Timesheet { get; set; }
        public Nullable<bool> Expense_Report { get; set; }
        public Nullable<bool> Expense_Report_Original { get; set; }
        public Nullable<bool> Invoice_Supplier { get; set; }
        public Nullable<bool> Invoice_Supplier_Original { get; set; }
        public Nullable<bool> Mandatory_Timesheet_Comment { get; set; }
        public Nullable<bool> Client_Written_Approval { get; set; }
        public string Client_Written_Approval_Desc { get; set; }
        public Nullable<bool> Client_Verbal_Approval { get; set; }
        public Nullable<bool> Interco { get; set; }
        public Nullable<bool> War { get; set; }
        public Nullable<bool> Multi_PO { get; set; }
        public Nullable<bool> Multi_Client { get; set; }
        public Nullable<bool> Joint_Venture { get; set; }
        public string End_Client_Name { get; set; }
    }
}
