//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningProject_Task
    {
        public int OpeningProject_Task_Id { get; set; }
        public int OpeningProject_Id { get; set; }
        public string Task_Number { get; set; }
        public string Task_Name { get; set; }
        public string Task_Description { get; set; }
        public string Task_Long_Name { get; set; }
        public Nullable<int> WBS_Level { get; set; }
        public Nullable<int> Task_Parent_Id { get; set; }
        public Nullable<int> Top_Task_Id { get; set; }
        public Nullable<System.DateTime> Task_Start_Date { get; set; }
        public Nullable<System.DateTime> Task_End_Date { get; set; }
        public string Task_Manager { get; set; }
        public Nullable<int> Task_Contract_Type_Id { get; set; }
        public Nullable<int> FeesMethod_Id { get; set; }
        public Nullable<int> ExpenditureMethod_Id { get; set; }
        public Nullable<decimal> Task_Revenue_Budget { get; set; }
        public Nullable<decimal> Task_Cost_Budget { get; set; }
        public Nullable<decimal> Task_Hrs_Budget { get; set; }
    }
}
