//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OS_Project_old
    {
        public int OS_Project_ID { get; set; }
        public string Project_Number { get; set; }
        public string Project_Description { get; set; }
        public bool Is_Master { get; set; }
        public string Project_Master { get; set; }
        public string PhaseCode { get; set; }
        public Nullable<byte> PhaseCodeType_ID { get; set; }
        public string Customer_Number { get; set; }
        public string Customer_Name { get; set; }
        public string Company { get; set; }
        public Nullable<int> Acct_Group_ID { get; set; }
        public Nullable<int> Acct_Center_ID { get; set; }
        public string Project_Mgr_Number { get; set; }
        public string End_Client_Name { get; set; }
        public string Contact_Client { get; set; }
        public Nullable<int> Approx_Amount { get; set; }
        public string Comments { get; set; }
        public string Initiated_By { get; set; }
        public Nullable<byte> Status_ID { get; set; }
        public string Last_Modification_User { get; set; }
        public Nullable<System.DateTime> Last_Modification_Date { get; set; }
        public string Program_Mgr_Number { get; set; }
        public string Billing_Address { get; set; }
        public string Shipping_Address { get; set; }
        public string Invoice_Email_Address { get; set; }
        public Nullable<int> Currency_ID { get; set; }
        public string Contract_Number { get; set; }
        public Nullable<System.DateTime> Required_Opening_Date { get; set; }
        public Nullable<int> Contract_Type_ID { get; set; }
        public Nullable<int> Program_ID { get; set; }
        public string Work_Type_ID { get; set; }
        public string Bill_Specialist_Number { get; set; }
        public Nullable<int> Office_Address_Id { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<int> Step_Reference { get; set; }
        public Nullable<System.DateTime> Archive_date { get; set; }
        public Nullable<byte> Doc_Status_ID { get; set; }
        public Nullable<System.DateTime> Doc_PostponedDate { get; set; }
    }
}
