//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int Program_ID { get; set; }
        public string Program_Description { get; set; }
        public string Work_Type_ID { get; set; }
        public string Program_Code { get; set; }
    }
}
