//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projet()
        {
            this.Projet_Repertoire = new HashSet<Projet_Repertoire>();
        }
    
        public string PRO_Id { get; set; }
        public int MOD_SEC_Id { get; set; }
        public int SER_Id { get; set; }
        public int PRO_Type { get; set; }
        public System.DateTime PRO_Date_Creation { get; set; }
        public string PRO_Parent { get; set; }
        public string PRO_Utilisateur { get; set; }
        public Nullable<System.DateTime> Time_Stamp { get; set; }
        public string PRO_Utilisateur_Modification { get; set; }
        public Nullable<int> ETA_PRO_ID { get; set; }
    
        public virtual Etat_Projet Etat_Projet { get; set; }
        public virtual Modele_Securite Modele_Securite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projet_Repertoire> Projet_Repertoire { get; set; }
        public virtual Serveur Serveur { get; set; }
    }
}
