//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_COMMENT
    {
        public int Project_id { get; set; }
        public int Version_ID { get; set; }
        public System.DateTime Period_Week_Date { get; set; }
        public System.DateTime DateModification { get; set; }
        public string LastUpdtBy { get; set; }
        public string Comment { get; set; }
        public string CommentType { get; set; }
        public string LastUpdtByKMRole { get; set; }
        public string full_name { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Project_Comment_Id { get; set; }
    
        public virtual XX_PROJECT XX_PROJECT { get; set; }
    }
}
