//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_COMMENT_TYPE
    {
        public string CommentType { get; set; }
        public string Comment_FR { get; set; }
        public string Comment_EN { get; set; }
        public System.DateTime start_date_active { get; set; }
        public System.DateTime end_date_active { get; set; }
    }
}
