//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_CONTROL_SECURITY
    {
        public string Security_Role { get; set; }
        public string Employee_Number { get; set; }
        public string full_name { get; set; }
        public string Unit_List { get; set; }
        public int Permission_ID { get; set; }
    
        public virtual PROJECT_CONTROL_SECURITY_ROLES PROJECT_CONTROL_SECURITY_ROLES { get; set; }
    }
}
