//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_RESOURCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECT_RESOURCE()
        {
            this.RESOURCE_HOURS = new HashSet<RESOURCE_HOURS>();
        }
    
        public int Project_Resource_id { get; set; }
        public int Project_ID { get; set; }
        public int Version_ID { get; set; }
        public System.DateTime Period_Week_Date { get; set; }
        public string Resource { get; set; }
        public decimal Cost_Rate { get; set; }
        public decimal Billing_Rate { get; set; }
        public string Employee_Number { get; set; }
    
        public virtual PROJECT_VERSION PROJECT_VERSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESOURCE_HOURS> RESOURCE_HOURS { get; set; }
    }
}
