//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCE_HOURS
    {
        public int Project_Resource_id { get; set; }
        public int Project_ID { get; set; }
        public int Version_ID { get; set; }
        public System.DateTime Period_Week_Date { get; set; }
        public int Task_id { get; set; }
        public decimal Hrs { get; set; }
    
        public virtual PROJECT_RESOURCE PROJECT_RESOURCE { get; set; }
        public virtual PROJECT_TASK PROJECT_TASK { get; set; }
    }
}
