//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RGE_Inclure_KM
    {
        public int id { get; set; }
        public string First_Name { get; set; }
        public string Employee_Number { get; set; }
        public string Organization { get; set; }
        public string Email_Address { get; set; }
        public Nullable<System.DateTime> DateDebutProjet { get; set; }
        public string NoProjet { get; set; }
    }
}
