//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serveur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serveur()
        {
            this.Projets = new HashSet<Projet>();
        }
    
        public int SER_Id { get; set; }
        public string SER_Nom { get; set; }
        public string SER_Ip { get; set; }
        public string SER_Description { get; set; }
        public string SER_Compagnie { get; set; }
        public string SER_Domaine { get; set; }
        public string SER_Chemin_Local { get; set; }
        public string SER_Utilisateur { get; set; }
        public string SER_Chemin_Partage { get; set; }
        public Nullable<int> SER_Map_Seulement { get; set; }
        public Nullable<byte> SER_Bilingue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projet> Projets { get; set; }
    }
}
