//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialMapServer
    {
        public int SrvId { get; set; }
        public int MapId { get; set; }
        public string Driver { get; set; }
        public string ServerName { get; set; }
        public string IP { get; set; }
        public string DescriptionFr { get; set; }
        public string DescriptionEn { get; set; }
        public string PathLocal { get; set; }
        public string PathPartage { get; set; }
        public string Compagnie { get; set; }
        public string Domaine { get; set; }
        public string Utilisateur { get; set; }
    }
}
