//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_liste_envois
    {
        public string Nom { get; set; }
        public string A_I { get; set; }
        public string CC_I { get; set; }
        public string A_MUN { get; set; }
        public string CC_MUN { get; set; }
        public string A_ENV { get; set; }
        public string CC_ENV { get; set; }
        public string A_complet { get; set; }
        public string CC_complet { get; set; }
        public string A_exclusions { get; set; }
        public string CC_exclusions { get; set; }
        public string A_A { get; set; }
        public string CC_ENV_A_715 { get; set; }
        public string CC_BATQC_A_715 { get; set; }
        public string CC_BATDirection_A_715 { get; set; }
        public string CC_BATOUEST_A_715 { get; set; }
        public string CC_MUN_A_715 { get; set; }
        public string CC_TRA_A_715 { get; set; }
        public string A_B { get; set; }
        public string CC_ENV_B_715 { get; set; }
        public string CC_BAT_B_715 { get; set; }
        public string CC_MUN_B_715 { get; set; }
        public string CC_TRA_B_715 { get; set; }
        public string A_C { get; set; }
        public string CC_ENV_C_715 { get; set; }
        public string CC_BATQC_C_715 { get; set; }
        public string CC_BATDirection_C_715 { get; set; }
        public string CC_BATOUEST_C_715 { get; set; }
        public string CC_MUN_C_715 { get; set; }
        public string CC_TRA_C_715 { get; set; }
        public string A_D { get; set; }
        public string CC_ENV_D_715 { get; set; }
        public string CC_BATQC_D_715 { get; set; }
        public string CC_BATDirection_D_715 { get; set; }
        public string CC_BATOUEST_D_715 { get; set; }
        public string CC_MUN_D_715 { get; set; }
        public string CC_TRA_D_715 { get; set; }
        public string A_F { get; set; }
        public string CC_ENV_F_715 { get; set; }
        public string CC_BATQC_F_715 { get; set; }
        public string CC_BATDirection_F_715 { get; set; }
        public string CC_BATOUEST_F_715 { get; set; }
        public string CC_MUN_F_715 { get; set; }
        public string CC_TRA_F_715 { get; set; }
        public string A_H { get; set; }
        public string CC_ENV_H_715 { get; set; }
        public string CC_BATQC_H_715 { get; set; }
        public string CC_BATDirection_H_715 { get; set; }
        public string CC_BATOUEST_H_715 { get; set; }
        public string CC_MUN_H_715 { get; set; }
        public string CC_TRA_H_715 { get; set; }
        public string A_J { get; set; }
        public string CC_ENV_J_715 { get; set; }
        public string CC_BATQC_J_715 { get; set; }
        public string CC_BATDirection_J_715 { get; set; }
        public string CC_BATOUEST_J_715 { get; set; }
        public string CC_MUN_J_715 { get; set; }
        public string CC_TRA_J_715 { get; set; }
        public int ID { get; set; }
        public string A_BAT { get; set; }
        public string CC_BAT { get; set; }
    }
}
