//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SuiviMandatEntitiesNew2 : DbContext
    {
        public SuiviMandatEntitiesNew2()
            : base("name=SuiviMandatEntitiesNew2")
        {
            // Get the ObjectContext related to this DbContext
            var objectContext = (this as IObjectContextAdapter).ObjectContext;

            // Sets the command timeout for all the commands
            objectContext.CommandTimeout = 0;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_tempTar> C_tempTar { get; set; }
        public virtual DbSet<BILLING_DETAIL_IF> BILLING_DETAIL_IF { get; set; }
        public virtual DbSet<BILLING_SUMMARY> BILLING_SUMMARY { get; set; }
        public virtual DbSet<BUSINESSUNIT_LIMITS> BUSINESSUNIT_LIMITS { get; set; }
        public virtual DbSet<COST_TABLE> COST_TABLE { get; set; }
        public virtual DbSet<DROPDOWN_LIST> DROPDOWN_LIST { get; set; }
        public virtual DbSet<DynamicColumnsForBillingSummary> DynamicColumnsForBillingSummaries { get; set; }
        public virtual DbSet<EMPLOYEE_GRIDSTATE> EMPLOYEE_GRIDSTATE { get; set; }
        public virtual DbSet<EmployeeCommisFacturation> EmployeeCommisFacturations { get; set; }
        public virtual DbSet<INSTRUCTION_STATUS> INSTRUCTION_STATUS { get; set; }
        public virtual DbSet<PERIOD_TLINX> PERIOD_TLINX { get; set; }
        public virtual DbSet<PROJECT_COMMENT_CONFIG> PROJECT_COMMENT_CONFIG { get; set; }
        public virtual DbSet<PROJECT_COMMENT_TASK> PROJECT_COMMENT_TASK { get; set; }
        public virtual DbSet<PROJECT_COMMENT_TYPE> PROJECT_COMMENT_TYPE { get; set; }
        public virtual DbSet<PROJECT_CONTROL_OFFICER> PROJECT_CONTROL_OFFICER { get; set; }
        public virtual DbSet<PROJECT_CONTROL_SECURITY> PROJECT_CONTROL_SECURITY { get; set; }
        public virtual DbSet<PROJECT_CONTROL_SECURITY_ROLES> PROJECT_CONTROL_SECURITY_ROLES { get; set; }
        public virtual DbSet<PROJECT_RESOURCE> PROJECT_RESOURCE { get; set; }
        public virtual DbSet<PROJECT_SM_HISTORY> PROJECT_SM_HISTORY { get; set; }
        public virtual DbSet<PROJECT_TASK> PROJECT_TASK { get; set; }
        public virtual DbSet<PROJECT_TASK_BRIDGE> PROJECT_TASK_BRIDGE { get; set; }
        public virtual DbSet<PROJECT_VERSION> PROJECT_VERSION { get; set; }
        public virtual DbSet<PROJECT_VERSION_COMMENT> PROJECT_VERSION_COMMENT { get; set; }
        public virtual DbSet<RESOURCE_HOURS> RESOURCE_HOURS { get; set; }
        public virtual DbSet<SETTING> SETTINGS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TTLinxPlus_Error_Log> TTLinxPlus_Error_Log { get; set; }
        public virtual DbSet<XX_BILL_DATA> XX_BILL_DATA { get; set; }
        public virtual DbSet<XX_COSTS_DATA> XX_COSTS_DATA { get; set; }
        public virtual DbSet<XX_CURRENCY_DAILY_RATES> XX_CURRENCY_DAILY_RATES { get; set; }
        public virtual DbSet<XX_PROJECT> XX_PROJECT { get; set; }
        public virtual DbSet<XX_PROJECT_DATA> XX_PROJECT_DATA { get; set; }
        public virtual DbSet<XX_PROJECT_KEYMEMBERS> XX_PROJECT_KEYMEMBERS { get; set; }
        public virtual DbSet<XX_PROJECT_TASKS_DATA> XX_PROJECT_TASKS_DATA { get; set; }
        public virtual DbSet<XX_PROJECT_TASKS_WBS> XX_PROJECT_TASKS_WBS { get; set; }
        public virtual DbSet<C__Comments> C__Comments { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<ProjectData_Tar_R91j> ProjectData_Tar_R91j { get; set; }
        public virtual DbSet<TEMP_BILL_DATA> TEMP_BILL_DATA { get; set; }
        public virtual DbSet<TEMP_COSTS_DATA> TEMP_COSTS_DATA { get; set; }
        public virtual DbSet<TEMP_CURRENCY_DAILY_RATES> TEMP_CURRENCY_DAILY_RATES { get; set; }
        public virtual DbSet<TEMP_PROJECT_DATA> TEMP_PROJECT_DATA { get; set; }
        public virtual DbSet<TEMP_PROJECT_KEYMEMBERS> TEMP_PROJECT_KEYMEMBERS { get; set; }
        public virtual DbSet<TEMP_PROJECT_TASKS_WBS> TEMP_PROJECT_TASKS_WBS { get; set; }
        public virtual DbSet<PROJECT_COMMENT> PROJECT_COMMENT { get; set; }
        public virtual DbSet<RGE_Inclure_KM> RGE_Inclure_KM { get; set; }
        public virtual DbSet<infoPermission> infoPermissions { get; set; }
        public virtual DbSet<TDT_Approbateurs> TDT_Approbateurs { get; set; }
        public virtual DbSet<TDT_Liste_de_taux_complet> TDT_Liste_de_taux_complet { get; set; }
        public virtual DbSet<TDT_Liste_de_taux_moyen> TDT_Liste_de_taux_moyen { get; set; }
        public virtual DbSet<TDT_Liste_de_taux_partielle> TDT_Liste_de_taux_partielle { get; set; }
        public virtual DbSet<TDT_Changements> TDT_Changements { get; set; }
        public virtual DbSet<EmployeeActif_Inactive> EmployeeActif_Inactive { get; set; }
        public virtual DbSet<ST_liste_envois> ST_liste_envois { get; set; }
        public virtual DbSet<ST_descriptions_listeEnvoie_types> ST_descriptions_listeEnvoie_types { get; set; }
        public virtual DbSet<TDT_TablePSW> TDT_TablePSW { get; set; }
    
        [DbFunction("SuiviMandatEntitiesNew2", "utvf_Summary_Service")]
        public virtual IQueryable<utvf_Summary_Service_Result> utvf_Summary_Service(Nullable<int> projectId, Nullable<System.DateTime> period, Nullable<int> version)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(System.DateTime));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<utvf_Summary_Service_Result>("[SuiviMandatEntitiesNew2].[utvf_Summary_Service](@projectId, @period, @version)", projectIdParameter, periodParameter, versionParameter);
        }
    
        [DbFunction("SuiviMandatEntitiesNew2", "utvf_SummaryByTaskService")]
        public virtual IQueryable<utvf_SummaryByTaskService_Result> utvf_SummaryByTaskService(Nullable<int> projectId, Nullable<System.DateTime> period, Nullable<int> version)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(System.DateTime));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<utvf_SummaryByTaskService_Result>("[SuiviMandatEntitiesNew2].[utvf_SummaryByTaskService](@projectId, @period, @version)", projectIdParameter, periodParameter, versionParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int usp_Age_Tar_New(Nullable<System.DateTime> pDateP)
        {
            var pDatePParameter = pDateP.HasValue ?
                new ObjectParameter("pDateP", pDateP) :
                new ObjectParameter("pDateP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Age_Tar_New", pDatePParameter);
        }
    
        public virtual ObjectResult<usp_AvgBillAndCostByProjTask_Result> usp_AvgBillAndCostByProjTask(Nullable<int> project_id, Nullable<int> task_id, Nullable<System.DateTime> period_week_date)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var task_idParameter = task_id.HasValue ?
                new ObjectParameter("task_id", task_id) :
                new ObjectParameter("task_id", typeof(int));
    
            var period_week_dateParameter = period_week_date.HasValue ?
                new ObjectParameter("Period_week_date", period_week_date) :
                new ObjectParameter("Period_week_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AvgBillAndCostByProjTask_Result>("usp_AvgBillAndCostByProjTask", project_idParameter, task_idParameter, period_week_dateParameter);
        }
    
        public virtual ObjectResult<string> usp_Billing_Filter_Distinct(string fieldname)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_Billing_Filter_Distinct", fieldnameParameter);
        }
    
        public virtual ObjectResult<usp_COST_TABLE_ResourcesList_Result> usp_COST_TABLE_ResourcesList(string filterText, string employeeId, string roleInfo)
        {
            var filterTextParameter = filterText != null ?
                new ObjectParameter("filterText", filterText) :
                new ObjectParameter("filterText", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(string));
    
            var roleInfoParameter = roleInfo != null ?
                new ObjectParameter("roleInfo", roleInfo) :
                new ObjectParameter("roleInfo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_COST_TABLE_ResourcesList_Result>("usp_COST_TABLE_ResourcesList", filterTextParameter, employeeIdParameter, roleInfoParameter);
        }
    
        public virtual int usp_CreateAlterDemo_Master_View()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CreateAlterDemo_Master_View");
        }
    
        public virtual ObjectResult<usp_getBillingAgentsList_Result> usp_getBillingAgentsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getBillingAgentsList_Result>("usp_getBillingAgentsList");
        }
    
        public virtual ObjectResult<usp_GetBillingDetail_Result> usp_GetBillingDetail(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetBillingDetail_Result>("usp_GetBillingDetail", projectIdParameter);
        }
    
        public virtual ObjectResult<usp_GetBillingSummary4Extract_Result> usp_GetBillingSummary4Extract(string employeeID, Nullable<bool> toutVoir, Nullable<int> projectId, string tBS)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var toutVoirParameter = toutVoir.HasValue ?
                new ObjectParameter("ToutVoir", toutVoir) :
                new ObjectParameter("ToutVoir", typeof(bool));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var tBSParameter = tBS != null ?
                new ObjectParameter("tBS", tBS) :
                new ObjectParameter("tBS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetBillingSummary4Extract_Result>("usp_GetBillingSummary4Extract", employeeIDParameter, toutVoirParameter, projectIdParameter, tBSParameter);
        }
    
        public virtual ObjectResult<usp_GetBillingSummary4Extract_NewTest_Result> usp_GetBillingSummary4Extract_NewTest(string employeeID, Nullable<bool> toutVoir, Nullable<int> projectId, string tBS)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var toutVoirParameter = toutVoir.HasValue ?
                new ObjectParameter("ToutVoir", toutVoir) :
                new ObjectParameter("ToutVoir", typeof(bool));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var tBSParameter = tBS != null ?
                new ObjectParameter("tBS", tBS) :
                new ObjectParameter("tBS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetBillingSummary4Extract_NewTest_Result>("usp_GetBillingSummary4Extract_NewTest", employeeIDParameter, toutVoirParameter, projectIdParameter, tBSParameter);
        }
    
        public virtual ObjectResult<usp_GetBillingSummary4ExtractClosing_Result> usp_GetBillingSummary4ExtractClosing(string employeeID, Nullable<bool> toutVoir, Nullable<int> projectId, string tBS)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var toutVoirParameter = toutVoir.HasValue ?
                new ObjectParameter("ToutVoir", toutVoir) :
                new ObjectParameter("ToutVoir", typeof(bool));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var tBSParameter = tBS != null ?
                new ObjectParameter("tBS", tBS) :
                new ObjectParameter("tBS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetBillingSummary4ExtractClosing_Result>("usp_GetBillingSummary4ExtractClosing", employeeIDParameter, toutVoirParameter, projectIdParameter, tBSParameter);
        }
    
        public virtual ObjectResult<usp_GetBillingSummary4ExtractClosing_01_Result> usp_GetBillingSummary4ExtractClosing_01(string employeeID, Nullable<bool> toutVoir, Nullable<int> projectId, string tBS)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var toutVoirParameter = toutVoir.HasValue ?
                new ObjectParameter("ToutVoir", toutVoir) :
                new ObjectParameter("ToutVoir", typeof(bool));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var tBSParameter = tBS != null ?
                new ObjectParameter("tBS", tBS) :
                new ObjectParameter("tBS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetBillingSummary4ExtractClosing_01_Result>("usp_GetBillingSummary4ExtractClosing_01", employeeIDParameter, toutVoirParameter, projectIdParameter, tBSParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> usp_getMaxDateForInstructionFact02()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("usp_getMaxDateForInstructionFact02");
        }
    
        public virtual ObjectResult<string> usp_getPeriodWeekDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_getPeriodWeekDate");
        }
    
        public virtual ObjectResult<usp_GetPlanif_4_Extraction_Result> usp_GetPlanif_4_Extraction(string kMID)
        {
            var kMIDParameter = kMID != null ?
                new ObjectParameter("KMID", kMID) :
                new ObjectParameter("KMID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetPlanif_4_Extraction_Result>("usp_GetPlanif_4_Extraction", kMIDParameter);
        }
    
        public virtual ObjectResult<usp_GetProjectPriority_Result> usp_GetProjectPriority(string eMP, string role, string panel, Nullable<decimal> pBC, Nullable<decimal> pNF, Nullable<decimal> pCAR, Nullable<decimal> pTAR)
        {
            var eMPParameter = eMP != null ?
                new ObjectParameter("EMP", eMP) :
                new ObjectParameter("EMP", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            var panelParameter = panel != null ?
                new ObjectParameter("panel", panel) :
                new ObjectParameter("panel", typeof(string));
    
            var pBCParameter = pBC.HasValue ?
                new ObjectParameter("pBC", pBC) :
                new ObjectParameter("pBC", typeof(decimal));
    
            var pNFParameter = pNF.HasValue ?
                new ObjectParameter("pNF", pNF) :
                new ObjectParameter("pNF", typeof(decimal));
    
            var pCARParameter = pCAR.HasValue ?
                new ObjectParameter("pCAR", pCAR) :
                new ObjectParameter("pCAR", typeof(decimal));
    
            var pTARParameter = pTAR.HasValue ?
                new ObjectParameter("pTAR", pTAR) :
                new ObjectParameter("pTAR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectPriority_Result>("usp_GetProjectPriority", eMPParameter, roleParameter, panelParameter, pBCParameter, pNFParameter, pCARParameter, pTARParameter);
        }
    
        public virtual ObjectResult<usp_GetProjectsNumberList_Result> usp_GetProjectsNumberList(string filterText)
        {
            var filterTextParameter = filterText != null ?
                new ObjectParameter("filterText", filterText) :
                new ObjectParameter("filterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectsNumberList_Result>("usp_GetProjectsNumberList", filterTextParameter);
        }
    
        public virtual ObjectResult<usp_GetProjectToClose_NoArchive_Result> usp_GetProjectToClose_NoArchive(string eMP, string role, Nullable<byte> toArchive)
        {
            var eMPParameter = eMP != null ?
                new ObjectParameter("EMP", eMP) :
                new ObjectParameter("EMP", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            var toArchiveParameter = toArchive.HasValue ?
                new ObjectParameter("ToArchive", toArchive) :
                new ObjectParameter("ToArchive", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectToClose_NoArchive_Result>("usp_GetProjectToClose_NoArchive", eMPParameter, roleParameter, toArchiveParameter);
        }
    
        public virtual ObjectResult<usp_GetRAF_4_Extraction_Result> usp_GetRAF_4_Extraction(string projectID, Nullable<int> versionID, Nullable<System.DateTime> periodWeekDate)
        {
            var projectIDParameter = projectID != null ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(string));
    
            var versionIDParameter = versionID.HasValue ?
                new ObjectParameter("versionID", versionID) :
                new ObjectParameter("versionID", typeof(int));
    
            var periodWeekDateParameter = periodWeekDate.HasValue ?
                new ObjectParameter("PeriodWeekDate", periodWeekDate) :
                new ObjectParameter("PeriodWeekDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetRAF_4_Extraction_Result>("usp_GetRAF_4_Extraction", projectIDParameter, versionIDParameter, periodWeekDateParameter);
        }
    
        public virtual ObjectResult<usp_GetSelectItemLists_Result> usp_GetSelectItemLists(string fieldname)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSelectItemLists_Result>("usp_GetSelectItemLists", fieldnameParameter);
        }
    
        public virtual ObjectResult<usp_GetServiceOffer_Result> usp_GetServiceOffer(string eMP)
        {
            var eMPParameter = eMP != null ?
                new ObjectParameter("EMP", eMP) :
                new ObjectParameter("EMP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetServiceOffer_Result>("usp_GetServiceOffer", eMPParameter);
        }
    
        public virtual int usp_GetSubTotal(string employeeID, Nullable<bool> toutVoir)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var toutVoirParameter = toutVoir.HasValue ?
                new ObjectParameter("ToutVoir", toutVoir) :
                new ObjectParameter("ToutVoir", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetSubTotal", employeeIDParameter, toutVoirParameter);
        }
    
        public virtual int usp_GetTLinxHomePageStats(string eMP, string role)
        {
            var eMPParameter = eMP != null ?
                new ObjectParameter("EMP", eMP) :
                new ObjectParameter("EMP", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetTLinxHomePageStats", eMPParameter, roleParameter);
        }
    
        public virtual ObjectResult<usp_GetView_AR_Result> usp_GetView_AR(string employeeNumber)
        {
            var employeeNumberParameter = employeeNumber != null ?
                new ObjectParameter("employeeNumber", employeeNumber) :
                new ObjectParameter("employeeNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetView_AR_Result>("usp_GetView_AR", employeeNumberParameter);
        }
    
        public virtual ObjectResult<usp_GetView_TAR_WAR_Result> usp_GetView_TAR_WAR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetView_TAR_WAR_Result>("usp_GetView_TAR_WAR");
        }
    
        public virtual int usp_GetView_TAR_WAR_NEW(string employeeNumber, Nullable<System.DateTime> pDateP)
        {
            var employeeNumberParameter = employeeNumber != null ?
                new ObjectParameter("employeeNumber", employeeNumber) :
                new ObjectParameter("employeeNumber", typeof(string));
    
            var pDatePParameter = pDateP.HasValue ?
                new ObjectParameter("pDateP", pDateP) :
                new ObjectParameter("pDateP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetView_TAR_WAR_NEW", employeeNumberParameter, pDatePParameter);
        }
    
        public virtual ObjectResult<usp_GetView_Unbilled_Result> usp_GetView_Unbilled(string employeeNumber, Nullable<System.DateTime> pDate)
        {
            var employeeNumberParameter = employeeNumber != null ?
                new ObjectParameter("employeeNumber", employeeNumber) :
                new ObjectParameter("employeeNumber", typeof(string));
    
            var pDateParameter = pDate.HasValue ?
                new ObjectParameter("pDate", pDate) :
                new ObjectParameter("pDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetView_Unbilled_Result>("usp_GetView_Unbilled", employeeNumberParameter, pDateParameter);
        }
    
        public virtual int usp_majBS_CommisFacturation(Nullable<int> projectID, string commisFacturation)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var commisFacturationParameter = commisFacturation != null ?
                new ObjectParameter("CommisFacturation", commisFacturation) :
                new ObjectParameter("CommisFacturation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_majBS_CommisFacturation", projectIDParameter, commisFacturationParameter);
        }
    
        public virtual ObjectResult<usp_PROJECTS_CONTROL_SECURITY_Result> usp_PROJECTS_CONTROL_SECURITY(Nullable<System.DateTime> currentPeriodWeekDate, string employeeId)
        {
            var currentPeriodWeekDateParameter = currentPeriodWeekDate.HasValue ?
                new ObjectParameter("currentPeriodWeekDate", currentPeriodWeekDate) :
                new ObjectParameter("currentPeriodWeekDate", typeof(System.DateTime));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PROJECTS_CONTROL_SECURITY_Result>("usp_PROJECTS_CONTROL_SECURITY", currentPeriodWeekDateParameter, employeeIdParameter);
        }
    
        public virtual int usp_RefreshTable_ProjectData_Tar_R91j()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RefreshTable_ProjectData_Tar_R91j");
        }
    
        public virtual int usp_SM_Quarterly_History(string sM_GeneratedBy, Nullable<System.DateTime> qDate, ObjectParameter success, ObjectParameter err_nbr, ObjectParameter err_msg)
        {
            var sM_GeneratedByParameter = sM_GeneratedBy != null ?
                new ObjectParameter("SM_GeneratedBy", sM_GeneratedBy) :
                new ObjectParameter("SM_GeneratedBy", typeof(string));
    
            var qDateParameter = qDate.HasValue ?
                new ObjectParameter("qDate", qDate) :
                new ObjectParameter("qDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SM_Quarterly_History", sM_GeneratedByParameter, qDateParameter, success, err_nbr, err_msg);
        }
    
        public virtual int usp_SM_Transfer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SM_Transfer");
        }
    
        public virtual int usp_TTLinxPlus_LogError(string tTAccount, string impersonationName, string controllerName, string controllerFunction, string innerException, string url)
        {
            var tTAccountParameter = tTAccount != null ?
                new ObjectParameter("TTAccount", tTAccount) :
                new ObjectParameter("TTAccount", typeof(string));
    
            var impersonationNameParameter = impersonationName != null ?
                new ObjectParameter("ImpersonationName", impersonationName) :
                new ObjectParameter("ImpersonationName", typeof(string));
    
            var controllerNameParameter = controllerName != null ?
                new ObjectParameter("ControllerName", controllerName) :
                new ObjectParameter("ControllerName", typeof(string));
    
            var controllerFunctionParameter = controllerFunction != null ?
                new ObjectParameter("ControllerFunction", controllerFunction) :
                new ObjectParameter("ControllerFunction", typeof(string));
    
            var innerExceptionParameter = innerException != null ?
                new ObjectParameter("InnerException", innerException) :
                new ObjectParameter("InnerException", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_TTLinxPlus_LogError", tTAccountParameter, impersonationNameParameter, controllerNameParameter, controllerFunctionParameter, innerExceptionParameter, urlParameter);
        }
    
        public virtual int usp_getActiveProjectToCloseByKM_noRole(string km, string lstPrj)
        {
            var kmParameter = km != null ?
                new ObjectParameter("Km", km) :
                new ObjectParameter("Km", typeof(string));
    
            var lstPrjParameter = lstPrj != null ?
                new ObjectParameter("lstPrj", lstPrj) :
                new ObjectParameter("lstPrj", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getActiveProjectToCloseByKM_noRole", kmParameter, lstPrjParameter);
        }
    
        public virtual ObjectResult<usp_getProject_ProgramManager_Result> usp_getProject_ProgramManager(string role)
        {
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getProject_ProgramManager_Result>("usp_getProject_ProgramManager", roleParameter);
        }
    
        public virtual ObjectResult<usp_getProject_ProgramManager_lastPeriodWeekDate_Result> usp_getProject_ProgramManager_lastPeriodWeekDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getProject_ProgramManager_lastPeriodWeekDate_Result>("usp_getProject_ProgramManager_lastPeriodWeekDate");
        }
    
        public virtual ObjectResult<usp_TDT_getProject_ProgramManager_Current_vs_Precedent_PeriodWeekDate_Result> usp_TDT_getProject_ProgramManager_Current_vs_Precedent_PeriodWeekDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TDT_getProject_ProgramManager_Current_vs_Precedent_PeriodWeekDate_Result>("usp_TDT_getProject_ProgramManager_Current_vs_Precedent_PeriodWeekDate");
        }
    
        public virtual ObjectResult<usp_TDT_getPrecedentPWD_Result> usp_TDT_getPrecedentPWD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TDT_getPrecedentPWD_Result>("usp_TDT_getPrecedentPWD");
        }
    
        public virtual ObjectResult<usp_TDT__getProject_ProgramManager_Precedent_vs_Current_PeriodWeekDate_Result> usp_TDT__getProject_ProgramManager_Precedent_vs_Current_PeriodWeekDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TDT__getProject_ProgramManager_Precedent_vs_Current_PeriodWeekDate_Result>("usp_TDT__getProject_ProgramManager_Precedent_vs_Current_PeriodWeekDate");
        }
    
        public virtual ObjectResult<usp_TT_Verif_KM_role_Result> usp_TT_Verif_KM_role(string acct_center, string role, Nullable<int> empNum)
        {
            var acct_centerParameter = acct_center != null ?
                new ObjectParameter("acct_center", acct_center) :
                new ObjectParameter("acct_center", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            var empNumParameter = empNum.HasValue ?
                new ObjectParameter("empNum", empNum) :
                new ObjectParameter("empNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TT_Verif_KM_role_Result>("usp_TT_Verif_KM_role", acct_centerParameter, roleParameter, empNumParameter);
        }
    
        public virtual ObjectResult<usp_TT_getProjetAvecDateDepasse_Result> usp_TT_getProjetAvecDateDepasse(string empRGE)
        {
            var empRGEParameter = empRGE != null ?
                new ObjectParameter("empRGE", empRGE) :
                new ObjectParameter("empRGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TT_getProjetAvecDateDepasse_Result>("usp_TT_getProjetAvecDateDepasse", empRGEParameter);
        }
    }
}
