//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAD_TT_Local_BPR
    {
        public string cn { get; set; }
        public string name { get; set; }
        public string mail { get; set; }
        public string sAMAccountName { get; set; }
        public string employeeID { get; set; }
        public string preferredLanguage { get; set; }
        public string company { get; set; }
        public string title { get; set; }
        public string department { get; set; }
        public string l { get; set; }
        public string physicalDeliveryOfficeName { get; set; }
        public string street { get; set; }
        public string postalCode { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime lastUpdt { get; set; }
    }
}
