//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDT_Approbateurs
    {
        public string Nom { get; set; }
        public string Division_de_marché { get; set; }
        public string autorisation { get; set; }
        public int ID { get; set; }
    }
}
