//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDT_Liste_de_taux_moyen
    {
        public string Nom_de_l_employé { get; set; }
        public string Numéro_employé_ { get; set; }
        public string Adresse_courriel { get; set; }
        public string Titre { get; set; }
        public string Division { get; set; }
        public string Commentaire { get; set; }
        public string Fait { get; set; }
        public string Retrait { get; set; }
        public int ID { get; set; }
    }
}
