//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_COSTS_DATA
    {
        public string company { get; set; }
        public int company_id { get; set; }
        public Nullable<int> exp_id { get; set; }
        public int project_id { get; set; }
        public string project_number { get; set; }
        public int task_id { get; set; }
        public string task_number { get; set; }
        public string employee_vend_name { get; set; }
        public string employee_vendor_number { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string unit_of_measure { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string expenditure_type { get; set; }
        public string expenditure_category { get; set; }
        public string nlr_code { get; set; }
        public string nlr_desc { get; set; }
        public string pa_period { get; set; }
        public string gl_period { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> Period_Week_Date { get; set; }
        public string txn_accum_id { get; set; }
        public string acct_center_name { get; set; }
        public Nullable<int> acct_center_number { get; set; }
    }
}
