//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TQEDocsToInsertInSubForlder
    {
        public string Rep_code { get; set; }
        public int Rep_Id { get; set; }
        public string SousRep_code { get; set; }
        public int SousRep_Id { get; set; }
        public string NumeroDoc { get; set; }
        public int itemId { get; set; }
    }
}
