//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_EmployeesPermissions
    {
        public int itemId { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> employeeNumber { get; set; }
        public string EmployeeFullName { get; set; }
        public string Role_Description { get; set; }
        public string Company { get; set; }
    }
}
