//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTIndex_FilesListDetailsTest
    {
        public string parentFolder { get; set; }
        public string fileName { get; set; }
        public string fileType { get; set; }
        public string fileDateCreation { get; set; }
        public string fileLastModificationDate { get; set; }
        public System.Guid pathFileId { get; set; }
    }
}
