//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTProjetSecurity
    {
        public string Security_Role { get; set; }
        public string Employee_Number { get; set; }
        public string Security_Desc { get; set; }
        public string FULL_NAME { get; set; }
        public string Company { get; set; }
    }
}
