//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_unite
    {
        public decimal id_type_unite { get; set; }
        public string categorie { get; set; }
        public string categorie_en { get; set; }
        public string categorie_esp { get; set; }
        public string unite { get; set; }
        public string unite_en { get; set; }
        public string unite_esp { get; set; }
    }
}
