//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class XX_PROJECT_KEYMEMBERS
    {
        public string company { get; set; }
        public int company_id { get; set; }
        public int project_id { get; set; }
        public string project_number { get; set; }
        public string full_name { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_names { get; set; }
        public string employee_number { get; set; }
        public string role { get; set; }
        public System.DateTime start_date_active { get; set; }
        public System.DateTime end_date_active { get; set; }
        public System.DateTime creation_date { get; set; }
        public Nullable<byte> hasChanged { get; set; }
    
        public virtual XX_PROJECT XX_PROJECT { get; set; }
    }
}
