//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class XX_PROJECT_TASKS_DATA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XX_PROJECT_TASKS_DATA()
        {
            this.PROJECT_TASK_BRIDGE = new HashSet<PROJECT_TASK_BRIDGE>();
            this.XX_BILL_DATA = new HashSet<XX_BILL_DATA>();
            this.XX_COSTS_DATA = new HashSet<XX_COSTS_DATA>();
        }
    
        public string company { get; set; }
        public Nullable<int> company_id { get; set; }
        public int project_id { get; set; }
        public int task_id { get; set; }
        public string gl_period { get; set; }
        public string project_number { get; set; }
        public string task_number { get; set; }
        public string task_name { get; set; }
        public string task_status_code { get; set; }
        public System.DateTime task_start_date { get; set; }
        public System.DateTime task_end_date { get; set; }
        public string billing_method { get; set; }
        public decimal cost_budget { get; set; }
        public decimal revenue_budget { get; set; }
        public decimal hrs_budget { get; set; }
        public decimal cost_ptd { get; set; }
        public decimal hrs_ptd { get; set; }
        public decimal cost_qtd { get; set; }
        public decimal hrs_qtd { get; set; }
        public decimal cost_ytd { get; set; }
        public decimal hrs_ytd { get; set; }
        public decimal cost_itd { get; set; }
        public decimal hrs_itd { get; set; }
        public decimal lbr_cost_itd { get; set; }
        public decimal sub_cost_itd { get; set; }
        public decimal odc_cost_itd { get; set; }
        public double cost_pct_complete { get; set; }
        public decimal total_billable { get; set; }
        public decimal lbr_billable { get; set; }
        public decimal sub_billable { get; set; }
        public decimal odc_billable { get; set; }
        public decimal event_billable { get; set; }
        public decimal nonbill_hrs_itd { get; set; }
        public decimal nonbill_itd { get; set; }
        public decimal total_billed { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime Period_Week_Date { get; set; }
        public System.DateTime pa_period_end_date { get; set; }
        public string task_lvl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_TASK_BRIDGE> PROJECT_TASK_BRIDGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XX_BILL_DATA> XX_BILL_DATA { get; set; }
        public virtual XX_PROJECT_DATA XX_PROJECT_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XX_COSTS_DATA> XX_COSTS_DATA { get; set; }
    }
}
