//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Views.ListeOffres {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListeProjetsRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListeProjetsRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TetraTech.TTProjetPlus.Views.ListeOffres.ListeProjetsRessources", typeof(ListeProjetsRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerte.
        /// </summary>
        public static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sauvegarde des changements effectués nécessitera la mise à jour de la sécurité des répertoires du projet et sera donc plus longue qu&apos;à l&apos;habitude..
        /// </summary>
        public static string alertMessage {
            get {
                return ResourceManager.GetString("alertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boomerang.
        /// </summary>
        public static string Boomerang {
            get {
                return ResourceManager.GetString("Boomerang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification du client.
        /// </summary>
        public static string ClientIdentification {
            get {
                return ResourceManager.GetString("ClientIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poursuivre.
        /// </summary>
        public static string continueA {
            get {
                return ResourceManager.GetString("continueA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copie le chemin du répertoire de projet.
        /// </summary>
        public static string CopyPath {
            get {
                return ResourceManager.GetString("CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur ce bouton, puis sur la touche Windows + E sur votre clavier et coller le contenu du presse-papier dans la barre d&apos;adresse.
        /// </summary>
        public static string CopyPath2 {
            get {
                return ResourceManager.GetString("CopyPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divers.
        /// </summary>
        public static string Divers {
            get {
                return ResourceManager.GetString("Divers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tâches et barèmes de facturation.
        /// </summary>
        public static string Duties {
            get {
                return ResourceManager.GetString("Duties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Génération d&apos;un numéro de projet.
        /// </summary>
        public static string GenerateProjectNumber {
            get {
                return ResourceManager.GetString("GenerateProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info-Projet.
        /// </summary>
        public static string InfoProject {
            get {
                return ResourceManager.GetString("InfoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des offres.
        /// </summary>
        public static string ListOffer {
            get {
                return ResourceManager.GetString("ListOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des projets.
        /// </summary>
        public static string ListProjet {
            get {
                return ResourceManager.GetString("ListProjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masquer les offres de services inactives.
        /// </summary>
        public static string maskInactive {
            get {
                return ResourceManager.GetString("maskInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masquer les projets inactifs.
        /// </summary>
        public static string maskInactiveProjects {
            get {
                return ResourceManager.GetString("maskInactiveProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes offres de services.
        /// </summary>
        public static string MyOffersList {
            get {
                return ResourceManager.GetString("MyOffersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes projets.
        /// </summary>
        public static string MyProjectsList {
            get {
                return ResourceManager.GetString("MyProjectsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La structure de répertoires n&apos;existe plus sur le serveur.
        /// </summary>
        public static string notExistingAnyMore {
            get {
                return ResourceManager.GetString("notExistingAnyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project folder structure no longer exists on the server.
        /// </summary>
        public static string notExistingAnyMore2 {
            get {
                return ResourceManager.GetString("notExistingAnyMore2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de l&apos;offre:.
        /// </summary>
        public static string offerDetails {
            get {
                return ResourceManager.GetString("offerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des offres de service.
        /// </summary>
        public static string OffersList {
            get {
                return ResourceManager.GetString("OffersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir: .
        /// </summary>
        public static string OpenPath {
            get {
                return ResourceManager.GetString("OpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails du projet:.
        /// </summary>
        public static string projectDetails {
            get {
                return ResourceManager.GetString("projectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification du projet.
        /// </summary>
        public static string ProjectIdentification {
            get {
                return ResourceManager.GetString("ProjectIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle du répertoire de projet.
        /// </summary>
        public static string ProjectModel {
            get {
                return ResourceManager.GetString("ProjectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouverture de projet.
        /// </summary>
        public static string ProjectOpening {
            get {
                return ResourceManager.GetString("ProjectOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiches projet.
        /// </summary>
        public static string projectSheet {
            get {
                return ResourceManager.GetString("projectSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des projets.
        /// </summary>
        public static string ProjectsList {
            get {
                return ResourceManager.GetString("ProjectsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermeture de projet.
        /// </summary>
        public static string ProjectToCloseTitle {
            get {
                return ResourceManager.GetString("ProjectToCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT Index (Archives).
        /// </summary>
        public static string TTIndex {
            get {
                return ResourceManager.GetString("TTIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
