//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TTProjetPlusResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TTProjetPlusResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TTProjetPlusResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès non autorisé..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string CancelDisplayName {
            get {
                return ResourceManager.GetString("CancelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opération annulée..
        /// </summary>
        internal static string CommandCanceled {
            get {
                return ResourceManager.GetString("CommandCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contient.
        /// </summary>
        internal static string contains {
            get {
                return ResourceManager.GetString("contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaaa-mm-jj.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format non valide pour la date (aaaa-mm-jj).
        /// </summary>
        internal static string DateValidatorMessage {
            get {
                return ResourceManager.GetString("DateValidatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masquer les projets fermés..
        /// </summary>
        internal static string DisplayActiveProjectsOnly {
            get {
                return ResourceManager.GetString("DisplayActiveProjectsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif.
        /// </summary>
        internal static string DocStatusId1 {
            get {
                return ResourceManager.GetString("DocStatusId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivée.
        /// </summary>
        internal static string DocStatusId2 {
            get {
                return ResourceManager.GetString("DocStatusId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report de l&apos;archivage de la documentation.
        /// </summary>
        internal static string DocStatusId3 {
            get {
                return ResourceManager.GetString("DocStatusId3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente de l&apos;archivage.
        /// </summary>
        internal static string DocStatusId4 {
            get {
                return ResourceManager.GetString("DocStatusId4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune documentation.
        /// </summary>
        internal static string DocStatusId5 {
            get {
                return ResourceManager.GetString("DocStatusId5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne contient pas.
        /// </summary>
        internal static string doesnotcontain {
            get {
                return ResourceManager.GetString("doesnotcontain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se termine par.
        /// </summary>
        internal static string endswith {
            get {
                return ResourceManager.GetString("endswith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est égal à.
        /// </summary>
        internal static string eq {
            get {
                return ResourceManager.GetString("eq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur: L&apos;appel a echoué, veuillez re-essayer!.
        /// </summary>
        internal static string ErrorMessageOther {
            get {
                return ResourceManager.GetString("ErrorMessageOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur:.
        /// </summary>
        internal static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre requête a généré une erreur . Pour plus d&apos;informations, veuillez contacter le CSTI..
        /// </summary>
        internal static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} n&apos;est pas une date..
        /// </summary>
        internal static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des colonnes.
        /// </summary>
        internal static string ManageColumns {
            get {
                return ResourceManager.GetString("ManageColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N’est pas égal à.
        /// </summary>
        internal static string neq {
            get {
                return ResourceManager.GetString("neq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre recherche ne correspond à aucun enregistrement.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de projet {0} ne correspond à aucun enregistrement.
        /// </summary>
        internal static string NoResultsForProjectNumber {
            get {
                return ResourceManager.GetString("NoResultsForProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offre de service.
        /// </summary>
        internal static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données en date du:.
        /// </summary>
        internal static string PeriodWeekDate {
            get {
                return ResourceManager.GetString("PeriodWeekDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de projet:.
        /// </summary>
        internal static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de projet.
        /// </summary>
        internal static string RAFMenuPageTitle {
            get {
                return ResourceManager.GetString("RAFMenuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi de projet.
        /// </summary>
        internal static string RAFPageTitle {
            get {
                return ResourceManager.GetString("RAFPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser la grille.
        /// </summary>
        internal static string ResetGrid {
            get {
                return ResourceManager.GetString("ResetGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir une date dans la liste.
        /// </summary>
        internal static string ResourceItemSelect {
            get {
                return ResourceManager.GetString("ResourceItemSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sauvegarde a été effectuée avec succès..
        /// </summary>
        internal static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrire au moins 2 caractères pour initier la  recherche.
        /// </summary>
        internal static string SearchLabel2Chars {
            get {
                return ResourceManager.GetString("SearchLabel2Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&apos;smallInfoText&apos;&gt;Inscrire au moins 2 caractères pour initier la  recherche&lt;/span&gt;.
        /// </summary>
        internal static string SearchLabel2Charshtml {
            get {
                return ResourceManager.GetString("SearchLabel2Charshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 100 enregistrements affichés.
        /// </summary>
        internal static string SearchMaxResults {
            get {
                return ResourceManager.GetString("SearchMaxResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;envoi de courriel a généré une erreur . Pour plus d&apos;informations, veuillez contacter le CSTI..
        /// </summary>
        internal static string SendMailErrorMessage {
            get {
                return ResourceManager.GetString("SendMailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commence par.
        /// </summary>
        internal static string startswith {
            get {
                return ResourceManager.GetString("startswith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT Projet +.
        /// </summary>
        internal static string TitleApplication {
            get {
                return ResourceManager.GetString("TitleApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour par.
        /// </summary>
        internal static string UpdatedByLabel {
            get {
                return ResourceManager.GetString("UpdatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
