//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Views.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TetraTech.TTProjetPlus.Views.Dashboard.Dashboard", typeof(Dashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projets actifs.
        /// </summary>
        public static string ActiveProjects {
            get {
                return ResourceManager.GetString("ActiveProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projets fermés mais non archivés.
        /// </summary>
        public static string ArchivingProjects {
            get {
                return ResourceManager.GetString("ArchivingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimé(s) en attente d&apos;approbation .
        /// </summary>
        public static string AwaitingEstimates {
            get {
                return ResourceManager.GetString("AwaitingEstimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimés budgétaires.
        /// </summary>
        public static string BudgetEstimates {
            get {
                return ResourceManager.GetString("BudgetEstimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comptes à recevoir (CAR).
        /// </summary>
        public static string CAR {
            get {
                return ResourceManager.GetString("CAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comptes a recevoir (CAR) &gt; 90 jours.
        /// </summary>
        public static string CAR90 {
            get {
                return ResourceManager.GetString("CAR90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet(s) en cours de fermeture.
        /// </summary>
        public static string ClosingProjects {
            get {
                return ResourceManager.GetString("ClosingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimés.
        /// </summary>
        public static string Estimates {
            get {
                return ResourceManager.GetString("Estimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoris.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure de répertoires.
        /// </summary>
        public static string FolderStructure {
            get {
                return ResourceManager.GetString("FolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue d&apos;ensemble.
        /// </summary>
        public static string GlobalView {
            get {
                return ResourceManager.GetString("GlobalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derniére mise-à-jour des données: .
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes projets.
        /// </summary>
        public static string MyProjects {
            get {
                return ResourceManager.GetString("MyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau projet.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derniére mise à jour des données.
        /// </summary>
        public static string PeriodWeekDate {
            get {
                return ResourceManager.GetString("PeriodWeekDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit période  à date (PAD).
        /// </summary>
        public static string ProfitToDate {
            get {
                return ResourceManager.GetString("ProfitToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionnaire de projet.
        /// </summary>
        public static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionnaire de projet.
        /// </summary>
        public static string ProjectManagerSection {
            get {
                return ResourceManager.GetString("ProjectManagerSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # de projet.
        /// </summary>
        public static string ProjectNumber {
            get {
                return ResourceManager.GetString("ProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projets.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre du projet.
        /// </summary>
        public static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string Revenu_Cost {
            get {
                return ResourceManager.GetString("Revenu_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travaux à risque (TAR).
        /// </summary>
        public static string TAR {
            get {
                return ResourceManager.GetString("TAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travaux à risque (TAR) &gt; 57 jours.
        /// </summary>
        public static string TAR57 {
            get {
                return ResourceManager.GetString("TAR57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non facturé.
        /// </summary>
        public static string Unbilled {
            get {
                return ResourceManager.GetString("Unbilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non facturés &gt; 60 jours.
        /// </summary>
        public static string Unbilled60 {
            get {
                return ResourceManager.GetString("Unbilled60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos priorités.
        /// </summary>
        public static string YourPriorities {
            get {
                return ResourceManager.GetString("YourPriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos rapports.
        /// </summary>
        public static string YourReports {
            get {
                return ResourceManager.GetString("YourReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos statistiques.
        /// </summary>
        public static string YourStatistics {
            get {
                return ResourceManager.GetString("YourStatistics", resourceCulture);
            }
        }
    }
}
