//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetraTech.TTProjetPlus.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class informations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal informations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TetraTech.TTProjetPlus.Views.Home.informations", typeof(informations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepter.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un tiret (-) sera ajouté automatiquement à la création du numéro de projet si vous choisissez l&apos;option Numérique ou Champ texte (ex: 12345-001 ou 12345-2022)..
        /// </summary>
        public static string additionalInfo {
            get {
                return ResourceManager.GetString("additionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;administrateur.
        /// </summary>
        public static string AdministratorName {
            get {
                return ResourceManager.GetString("AdministratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabétique.
        /// </summary>
        public static string Alphabetic {
            get {
                return ResourceManager.GetString("Alphabetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le titre choisi est déjà attribué à un autre projet. Veuillez le modifier..
        /// </summary>
        public static string alreadyExistingTitleError {
            get {
                return ResourceManager.GetString("alreadyExistingTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant approximatif.
        /// </summary>
        public static string ApproximateAmount {
            get {
                return ResourceManager.GetString("ApproximateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;archivage.
        /// </summary>
        public static string archivingDate {
            get {
                return ResourceManager.GetString("archivingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sécurité de base.
        /// </summary>
        public static string BasicSecurity {
            get {
                return ResourceManager.GetString("BasicSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité d’affaires.
        /// </summary>
        public static string BusinessUnit {
            get {
                return ResourceManager.GetString("BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez préciser l&apos;unité d’affaires..
        /// </summary>
        public static string BusinessUnitError {
            get {
                return ResourceManager.GetString("BusinessUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to par.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir un modèle.
        /// </summary>
        public static string chooseModel {
            get {
                return ResourceManager.GetString("chooseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir un modèle de sélection (optionnel)....
        /// </summary>
        public static string chooseSelectionModel {
            get {
                return ResourceManager.GetString("chooseSelectionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de client.
        /// </summary>
        public static string ClienNumber {
            get {
                return ResourceManager.GetString("ClienNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des clients.
        /// </summary>
        public static string clientList {
            get {
                return ResourceManager.GetString("clientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du client.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez fournir un nom de client..
        /// </summary>
        public static string ClientNameError {
            get {
                return ResourceManager.GetString("ClientNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez fournir un numéro de client..
        /// </summary>
        public static string ClientNumberError {
            get {
                return ResourceManager.GetString("ClientNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de phase.
        /// </summary>
        public static string CodeOfPhase {
            get {
                return ResourceManager.GetString("CodeOfPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compagnie.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez préciser la compagnie..
        /// </summary>
        public static string CompanyError {
            get {
                return ResourceManager.GetString("CompanyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact client.
        /// </summary>
        public static string ContactClient {
            get {
                return ResourceManager.GetString("ContactClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir en projet.
        /// </summary>
        public static string ConvertToProject {
            get {
                return ResourceManager.GetString("ConvertToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier le chemin du répertoire de projet.
        /// </summary>
        public static string copyPath {
            get {
                return ResourceManager.GetString("copyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour ouvrir un répertoire de projet.
        /// </summary>
        public static string CopyPath3 {
            get {
                return ResourceManager.GetString("CopyPath3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur ce bouton, puis sur la touche Windows + E de votre clavier et coller le contenu du presse-papier dans la barre d&apos;adresse.
        /// </summary>
        public static string CopyPath4 {
            get {
                return ResourceManager.GetString("CopyPath4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet créé le.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une structure de projet.
        /// </summary>
        public static string CreateFolderStrucutre {
            get {
                return ResourceManager.GetString("CreateFolderStrucutre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de bien vouloir remplir le(s) champ(s) suivant(s).
        /// </summary>
        public static string DF_message1 {
            get {
                return ResourceManager.GetString("DF_message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier une date de report de l&apos;archivage.
        /// </summary>
        public static string DF_message10 {
            get {
                return ResourceManager.GetString("DF_message10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier le titre de l&apos;offre..
        /// </summary>
        public static string DF_message2 {
            get {
                return ResourceManager.GetString("DF_message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier le numéro du client..
        /// </summary>
        public static string DF_message3 {
            get {
                return ResourceManager.GetString("DF_message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier le nom du client..
        /// </summary>
        public static string DF_message4 {
            get {
                return ResourceManager.GetString("DF_message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier la compagnie..
        /// </summary>
        public static string DF_message5 {
            get {
                return ResourceManager.GetString("DF_message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier l&apos;unité d&apos;affaires..
        /// </summary>
        public static string DF_message6 {
            get {
                return ResourceManager.GetString("DF_message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier l&apos;organisation..
        /// </summary>
        public static string DF_message7 {
            get {
                return ResourceManager.GetString("DF_message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier le gestionnaire de projet..
        /// </summary>
        public static string DF_message8 {
            get {
                return ResourceManager.GetString("DF_message8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La mise à jour du projet a réussi! Merci de laisser la page principale se recharger afin de montrer vos  modifications..
        /// </summary>
        public static string DF_message9 {
            get {
                return ResourceManager.GetString("DF_message9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir une des trois options....
        /// </summary>
        public static string DF_op1 {
            get {
                return ResourceManager.GetString("DF_op1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir une des deux options....
        /// </summary>
        public static string DF_op1a {
            get {
                return ResourceManager.GetString("DF_op1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation active.
        /// </summary>
        public static string DF_op2 {
            get {
                return ResourceManager.GetString("DF_op2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente de l&apos;archivage.
        /// </summary>
        public static string DF_op3 {
            get {
                return ResourceManager.GetString("DF_op3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report de l&apos;archivage de la documentation.
        /// </summary>
        public static string DF_op4 {
            get {
                return ResourceManager.GetString("DF_op4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune documentation.
        /// </summary>
        public static string DF_op5 {
            get {
                return ResourceManager.GetString("DF_op5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation archivée.
        /// </summary>
        public static string DF_op6 {
            get {
                return ResourceManager.GetString("DF_op6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut de la documentation.
        /// </summary>
        public static string docStatus {
            get {
                return ResourceManager.GetString("docStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dans quelle langue voulez vous envoyer le courriel automatique?.
        /// </summary>
        public static string emailLang {
            get {
                return ResourceManager.GetString("emailLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est-ce que c&apos;est un projet en vérification diligente?.
        /// </summary>
        public static string EnvDiligente {
            get {
                return ResourceManager.GetString("EnvDiligente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un projet enfant associé à ce projet maître, à cette phase et cette compagnie existe déjà. Veuillez modifier ces paramètres..
        /// </summary>
        public static string existingChild {
            get {
                return ResourceManager.GetString("existingChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La création de projet a échoué!.
        /// </summary>
        public static string failedCreation {
            get {
                return ResourceManager.GetString("failedCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Final.
        /// </summary>
        public static string FinalClient {
            get {
                return ResourceManager.GetString("FinalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration des répertoires.
        /// </summary>
        public static string FolderStructure {
            get {
                return ResourceManager.GetString("FolderStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations générales.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez préciser la liaison à un projet maître..
        /// </summary>
        public static string HasAMasterProjectError {
            get {
                return ResourceManager.GetString("HasAMasterProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID du projet.
        /// </summary>
        public static string IDProject {
            get {
                return ResourceManager.GetString("IDProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initié par.
        /// </summary>
        public static string InitiatedBy {
            get {
                return ResourceManager.GetString("InitiatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation interne.
        /// </summary>
        public static string internalOrg {
            get {
                return ResourceManager.GetString("internalOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est-ce un projet lié à un projet maître.
        /// </summary>
        public static string IsItLinkedToMasterProject {
            get {
                return ResourceManager.GetString("IsItLinkedToMasterProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière modification le.
        /// </summary>
        public static string lastModif {
            get {
                return ResourceManager.GetString("lastModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet lié.
        /// </summary>
        public static string LinkedProject {
            get {
                return ResourceManager.GetString("LinkedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des offres de services.
        /// </summary>
        public static string ListOfOffers {
            get {
                return ResourceManager.GetString("ListOfOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des projets.
        /// </summary>
        public static string ListOfProjects {
            get {
                return ResourceManager.GetString("ListOfProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ obligatoire.
        /// </summary>
        public static string MandatoryField {
            get {
                return ResourceManager.GetString("MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet maître.
        /// </summary>
        public static string Masterproject {
            get {
                return ResourceManager.GetString("Masterproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier le nom du projet maître..
        /// </summary>
        public static string masterProjectNameError {
            get {
                return ResourceManager.GetString("masterProjectNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez fournir les détails du projet maître et le code la phase voulue.
        /// </summary>
        public static string MasterProjectNumber {
            get {
                return ResourceManager.GetString("MasterProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de bien vouloir remplir ou modifier le(s) champ(s) suivant(s):.
        /// </summary>
        public static string message1 {
            get {
                return ResourceManager.GetString("message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;arborescence du projet n&apos;a pas pu être insérée dans la base de données..
        /// </summary>
        public static string message1a {
            get {
                return ResourceManager.GetString("message1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les fichiers demandés pour le projet n&apos;ont pas pu être ajoutés..
        /// </summary>
        public static string message2a {
            get {
                return ResourceManager.GetString("message2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les sécurités n&apos;ont pas pu être appliquées aux dossiers de projet sur le serveur demandé..
        /// </summary>
        public static string message3a {
            get {
                return ResourceManager.GetString("message3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une structure de répertoires portant ce numéro existe déjà. Veuillez contacter le CSTI. .
        /// </summary>
        public static string message4a {
            get {
                return ResourceManager.GetString("message4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez fournir le courriel du chargé de projet client..
        /// </summary>
        public static string MissingCourriel {
            get {
                return ResourceManager.GetString("MissingCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier le modèle..
        /// </summary>
        public static string modelError {
            get {
                return ResourceManager.GetString("modelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string mp_client {
            get {
                return ResourceManager.GetString("mp_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner un projet maître ou cliquez sur le bouton &quot;Annuler&quot;.
        /// </summary>
        public static string mp_message1 {
            get {
                return ResourceManager.GetString("mp_message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant....
        /// </summary>
        public static string mp_message2 {
            get {
                return ResourceManager.GetString("mp_message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun résultat pour cette requête....
        /// </summary>
        public static string mp_null {
            get {
                return ResourceManager.GetString("mp_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de Projet.
        /// </summary>
        public static string mp_number {
            get {
                return ResourceManager.GetString("mp_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string mp_org {
            get {
                return ResourceManager.GetString("mp_org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critère de recherche....
        /// </summary>
        public static string mp_search {
            get {
                return ResourceManager.GetString("mp_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre de projet.
        /// </summary>
        public static string mp_title {
            get {
                return ResourceManager.GetString("mp_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro du projet maître.
        /// </summary>
        public static string MPNumber {
            get {
                return ResourceManager.GetString("MPNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche de projet maitre.
        /// </summary>
        public static string MPSearch {
            get {
                return ResourceManager.GetString("MPSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La documentation est déjà archivée. Si vous avez besoin que la structure soit désarchivée, veuillez communiquer avec le CSTI via courriel à SRA@tetratech.com, par le portail via l’Intranet ou par téléphone au 1-866-208-5234..
        /// </summary>
        public static string MsgArchived {
            get {
                return ResourceManager.GetString("MsgArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout d&apos;un nouveau client.
        /// </summary>
        public static string newClient {
            get {
                return ResourceManager.GetString("newClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création du numéro de projet.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau # Projet.
        /// </summary>
        public static string NewProjectBC {
            get {
                return ResourceManager.GetString("NewProjectBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No du projet maître.
        /// </summary>
        public static string NoMasterProject {
            get {
                return ResourceManager.GetString("NoMasterProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n y a pas de modèle de sélection pour ce modèle de serveur.
        /// </summary>
        public static string noModelForThisServer {
            get {
                return ResourceManager.GetString("noModelForThisServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune valeur.
        /// </summary>
        public static string noResult2 {
            get {
                return ResourceManager.GetString("noResult2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce client n&apos;existe pas.
        /// </summary>
        public static string notExistingClient {
            get {
                return ResourceManager.GetString("notExistingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce projet maître n&apos;existe pas..
        /// </summary>
        public static string notExistingMP {
            get {
                return ResourceManager.GetString("notExistingMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce gestionnaire de programme n&apos;existe pas.
        /// </summary>
        public static string notExistingProgramManager {
            get {
                return ResourceManager.GetString("notExistingProgramManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce gestionnaire de projet n&apos;existe pas.
        /// </summary>
        public static string notExistingProjectManager {
            get {
                return ResourceManager.GetString("notExistingProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro généré.
        /// </summary>
        public static string NumberGenerated {
            get {
                return ResourceManager.GetString("NumberGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No de client / Nom de client.
        /// </summary>
        public static string NumberNameClient {
            get {
                return ResourceManager.GetString("NumberNameClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numérique.
        /// </summary>
        public static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Génération de numéro de projet.
        /// </summary>
        public static string NumeroProjetGeneration {
            get {
                return ResourceManager.GetString("NumeroProjetGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offres et projets.
        /// </summary>
        public static string OffersAndProjects {
            get {
                return ResourceManager.GetString("OffersAndProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bureau.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir:.
        /// </summary>
        public static string openStruct {
            get {
                return ResourceManager.GetString("openStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string ORG {
            get {
                return ResourceManager.GetString("ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez préciser quelle est l&apos;organisation.
        /// </summary>
        public static string ORGError {
            get {
                return ResourceManager.GetString("ORGError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière mise à jour des données.
        /// </summary>
        public static string PeriodWeekDate {
            get {
                return ResourceManager.GetString("PeriodWeekDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière mise à jour des données.
        /// </summary>
        public static string PeriodWeekDate1 {
            get {
                return ResourceManager.GetString("PeriodWeekDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier la phase..
        /// </summary>
        public static string phaseError {
            get {
                return ResourceManager.GetString("phaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de report de l&apos;archivage.
        /// </summary>
        public static string postponeDate {
            get {
                return ResourceManager.GetString("postponeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Précédent.
        /// </summary>
        public static string Precedent {
            get {
                return ResourceManager.GetString("Precedent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’exécution de votre requête a rencontré un ou des problèmes!.
        /// </summary>
        public static string problemExcecution {
            get {
                return ResourceManager.GetString("problemExcecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionnaire de programme.
        /// </summary>
        public static string ProgramMgr {
            get {
                return ResourceManager.GetString("ProgramMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description du projet.
        /// </summary>
        public static string projectDescription {
            get {
                return ResourceManager.GetString("projectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des projets.
        /// </summary>
        public static string projectList {
            get {
                return ResourceManager.GetString("projectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel du chargé de projet.
        /// </summary>
        public static string ProjectManagerCourriel {
            get {
                return ResourceManager.GetString("ProjectManagerCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du chargé de projet client.
        /// </summary>
        public static string ProjectManagerName {
            get {
                return ResourceManager.GetString("ProjectManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Requis pour la satisfaction client).
        /// </summary>
        public static string ProjectMangerReg {
            get {
                return ResourceManager.GetString("ProjectMangerReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des gestionnaires de projets.
        /// </summary>
        public static string projectManList {
            get {
                return ResourceManager.GetString("projectManList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionnaire de projet.
        /// </summary>
        public static string ProjectMgr {
            get {
                return ResourceManager.GetString("ProjectMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez fournir un nom pour le gestionnaire de projet..
        /// </summary>
        public static string ProjectMgrError {
            get {
                return ResourceManager.GetString("ProjectMgrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez spécifier le nom du projet..
        /// </summary>
        public static string projectNameError {
            get {
                return ResourceManager.GetString("projectNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperçu de numéro.
        /// </summary>
        public static string ProjectNumberAnticipated {
            get {
                return ResourceManager.GetString("ProjectNumberAnticipated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Génération d’un numéro de projet.
        /// </summary>
        public static string projectnumberCreation {
            get {
                return ResourceManager.GetString("projectnumberCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez fournir un numéro de projet.
        /// </summary>
        public static string ProjectNumberError {
            get {
                return ResourceManager.GetString("ProjectNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project opening.
        /// </summary>
        public static string ProjectOpening {
            get {
                return ResourceManager.GetString("ProjectOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du responsable de projet.
        /// </summary>
        public static string projectReponsible {
            get {
                return ResourceManager.GetString("projectReponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Références et commentaires.
        /// </summary>
        public static string RefAndComments {
            get {
                return ResourceManager.GetString("RefAndComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès restreint. Veuillez adresser une demande d&apos;autorisation à l&apos;un des administrateurs suivants en cliquant sur l&apos;icône présentant une enveloppe vis-à-vis la compagnie et l&apos;unité d&apos;affaire vous concernant..
        /// </summary>
        public static string restricted {
            get {
                return ResourceManager.GetString("restricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résumé.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle de sécurité.
        /// </summary>
        public static string SecurityModel {
            get {
                return ResourceManager.GetString("SecurityModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez preciser quel est le modèle de sécurité.
        /// </summary>
        public static string SecurityModelError {
            get {
                return ResourceManager.GetString("SecurityModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle de sélection.
        /// </summary>
        public static string SelectionModel {
            get {
                return ResourceManager.GetString("SelectionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le code de la phase.
        /// </summary>
        public static string SelectPhaseCode {
            get {
                return ResourceManager.GetString("SelectPhaseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer l&apos;information par courriel.
        /// </summary>
        public static string sendMail {
            get {
                return ResourceManager.GetString("sendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveur.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez fournir un nom de serveur..
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez préciser quel est le modèle .
        /// </summary>
        public static string ServerModelError {
            get {
                return ResourceManager.GetString("ServerModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province,état.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin de la structure de répertoires.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin de la structure de répertoires.
        /// </summary>
        public static string structPath {
            get {
                return ResourceManager.GetString("structPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La création de projet a réussi!.
        /// </summary>
        public static string successCreation {
            get {
                return ResourceManager.GetString("successCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le processus de création d&apos;arborescence sur le serveur a réussi!.
        /// </summary>
        public static string successTree {
            get {
                return ResourceManager.GetString("successTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ texte de maximum 5 caractères.
        /// </summary>
        public static string TextField {
            get {
                return ResourceManager.GetString("TextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Client.
        /// </summary>
        public static string the_client {
            get {
                return ResourceManager.GetString("the_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astuces.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez fournir un titre de projet..
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre du projet.
        /// </summary>
        public static string TitleOS {
            get {
                return ResourceManager.GetString("TitleOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un courriel résumant les informations du numéro de projet a été envoyé aux adresses courriels suivantes.
        /// </summary>
        public static string TQEEmailAddressesList {
            get {
                return ResourceManager.GetString("TQEEmailAddressesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande est en traitement....
        /// </summary>
        public static string Treatement {
            get {
                return ResourceManager.GetString("Treatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT Projet + .
        /// </summary>
        public static string TTProject {
            get {
                return ResourceManager.GetString("TTProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de projet.
        /// </summary>
        public static string TypeOfProject {
            get {
                return ResourceManager.GetString("TypeOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre numéro est:.
        /// </summary>
        public static string YourNumberIs {
            get {
                return ResourceManager.GetString("YourNumberIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal.
        /// </summary>
        public static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
